# Values for kirby design branch

replicaCount: 1

image:
  pullSecret: regcred

ingress:
  annotations:
    kubernetes.io/ingress.class: 'addon-http-application-routing'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=31536000";
      more_set_headers "Access-Control-Allow-Origin: *";
  tls:
    enable: true
    secret: branch-tls-secret
