changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
        - fix
    - title: Everything else
      labels:
        - "*"
