import { existsSync, mkdirSync, readFileSync, writeFile } from 'fs';
import path from 'path';
import prettier from 'prettier';
import { ESLint } from 'eslint';

import {
  eventToPropertyName,
  getElementMetadata,
  getJsdocDescription,
  getJsdocDescriptionDeprecated,
} from './utils/cem-helper-functions';
import { LitCustomElement } from './utils';

/********** Script execution **********/

const CORE_LIB_PATH = 'libs/core';
const ANGULAR_LIB_PATH = 'libs/angular';
const GENERATED_COMPONENT_START_REGION = '// START_OF_AUTO_GENERATED_COMPONENT';
const CORE_PACKAGE_JSON_NAME = JSON.parse(
  readFileSync(path.resolve(`${CORE_LIB_PATH}/package.json`), 'utf8')
).name;

const elementMetadata: LitCustomElement[] = getElementMetadata(CORE_LIB_PATH);

elementMetadata.forEach(async (element) => {
  const { tagName, tagNameWithoutPrefix } = element;
  const componentDir = `${ANGULAR_LIB_PATH}/${tagNameWithoutPrefix}/src`;
  const componentFilePath = `${componentDir}/${tagNameWithoutPrefix}.component.ts`;
  const componentPublicApiPath = `${componentDir}/public_api.ts`;

  mkdirSync(componentDir, { recursive: true });

  await writeComponentFile(element, tagName, componentFilePath).catch((error) => {
    console.error(error);
  });

  await writePublicApiFile(element, tagName, componentPublicApiPath).catch((error) => {
    console.error(error);
  });
});

/********** Angular-related helper functions **********/

async function writeComponentFile(element: LitCustomElement, tagName: string, filePath: string) {
  const component = await generateComponentSource(element);

  // merge any manually added imports with the auto-generated component imports
  const componentImports = existsSync(filePath)
    ? getExistingImports(filePath)
    : getAutogeneratedImports(element);

  const manualComponentCode = getManualComponentCode(filePath);

  const componentWithImports = componentImports + component + '\n' + manualComponentCode;

  const lintedComponentWithImports = await formatWithEslint(componentWithImports, tagName);

  writeFile(filePath, lintedComponentWithImports, 'utf8', (err) => {
    if (err) throw err;
    console.log(`Angular component file for ${tagName} has been created.`);
  });
}

async function writePublicApiFile(element: LitCustomElement, tagName: string, filePath: string) {
  const publicApiSource = await generatePublicApiSource(element);

  const formattedPublicApiSource = await formatWithPrettier(publicApiSource);

  writeFile(filePath, formattedPublicApiSource, 'utf8', (err) => {
    if (err) throw err;
    console.log(`Public API file for ${tagName} has been created.`);
  });
}

function getManualComponentCode(filePath: string): string {
  if (!existsSync(filePath)) return '';
  const existingComponent = readFileSync(filePath, 'utf8');
  const manualCodeStartIndex = existingComponent.indexOf('// START_OF_MANUAL_COMPONENT_CODE');
  if (manualCodeStartIndex !== -1) {
    return existingComponent.substring(manualCodeStartIndex);
  }
  return '';
}

function getExistingImports(componentFile: string) {
  const existingComponent = readFileSync(componentFile, 'utf8');
  const autoGeneratedComponentStartIndex = existingComponent.indexOf(
    GENERATED_COMPONENT_START_REGION
  );

  if (autoGeneratedComponentStartIndex !== -1) {
    const imports = existingComponent.substring(
      0,
      autoGeneratedComponentStartIndex + GENERATED_COMPONENT_START_REGION.length
    );

    return imports;
  }
  return '';
}

function getAutogeneratedImports(element: LitCustomElement) {
  const elementEntryPoint = `'${CORE_PACKAGE_JSON_NAME}/${element.tagNameWithoutPrefix}'`;

  return `import { ChangeDetectionStrategy, ChangeDetectorRef, Component, ElementRef, EventEmitter, Input, NgZone, Output } from '@angular/core';
    import type { ${element.name} } from ${elementEntryPoint};
    ${GENERATED_COMPONENT_START_REGION}`;
}

function getInputProperties(element: LitCustomElement, baseProperties: string[] = []) {
  if (!element.properties) return '';
  return element.properties
    .map(
      (property) => `
        ${getJsdocDescription(property)} ${getJsdocDescriptionDeprecated(property)}
        @Input()
        ${baseProperties.includes(property.name) ? 'override ' : ''}set ${property.name}(v: ${property.type?.text}) {
          this.ngZone.runOutsideAngular(() => (this.el.${property.name} = v));
        }

        ${baseProperties.includes(property.name) ? 'override ' : ''}get ${property.name}(): ${property.type?.text} {
          return this.el.${property.name};
        }`
    )
    .join('\n');
}

// Helper: Find all getter/setter names in base component file
function getBaseComponentProperties(baseComponentPath: string): string[] {
  if (!existsSync(baseComponentPath)) return [];
  const content = readFileSync(baseComponentPath, 'utf8');
  // Find all get/set propertyName() in the file
  const matches = [...content.matchAll(/(?:get|set)\s+([a-zA-Z0-9_]+)\s*\(/g)];
  return Array.from(new Set(matches.map((m) => m[1])));
}

function getOutputProperties(element: LitCustomElement) {
  if (!element.events) return '';
  return element.events
    .map((event) => `@Output() ${eventToPropertyName(event.name)} = new EventEmitter<unknown>();`)
    .join('\n');
}

function getEventListeners(element: LitCustomElement) {
  if (!element.events) return '';
  return element.events
    .map(
      (event) => `
        this.el.addEventListener('${event.name}', (e: Event) => {
          this.${eventToPropertyName(event.name)}.emit(e);
        });`
    )
    .join('\n');
}

async function formatWithPrettier(code: string) {
  const filePath = await prettier.resolveConfigFile();
  if (!filePath) return code;
  const options = await prettier.resolveConfig(filePath);
  return prettier.format(code, { ...options, parser: 'typescript' });
}

async function generateComponentSource(element: LitCustomElement) {
  const { name, tagName, tagNameWithoutPrefix } = element;
  const angularComponentName = name.replace('Element', 'Component');
  const componentDir = path.join('libs/angular', tagNameWithoutPrefix, 'src');
  const baseComponentPath = path.join(componentDir, `${tagNameWithoutPrefix}-base.component.ts`);
  const hasBaseComponent = existsSync(baseComponentPath);

  const baseClassName = hasBaseComponent
    ? `Kirby${tagNameWithoutPrefix
        .split('-')
        .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
        .join('')}BaseComponent`
    : '';
  const extendsBase = hasBaseComponent ? `extends ${baseClassName} ` : '';
  const superCall = hasBaseComponent ? 'super();\n    ' : '';

  // Find all base properties (getters/setters)
  const baseProperties = hasBaseComponent ? getBaseComponentProperties(baseComponentPath) : [];

  const componentSource = `
    // AUTO-GENERATED - Any missing type imports can be added manually above, but do not change component source
    @Component({
      selector: '${tagName}',
      template: '<ng-content></ng-content>',
      changeDetection: ChangeDetectionStrategy.OnPush,
    })
    export class ${angularComponentName} ${extendsBase}{
      private el: ${name};

      constructor(private e: ElementRef<${name}>, private ngZone: NgZone, private cdr: ChangeDetectorRef) {
        ${superCall}this.el = this.e.nativeElement;
        this.cdr.detach();

        ${getEventListeners(element)}
      }

      ${getInputProperties(element, baseProperties)}
      ${getOutputProperties(element)}
    }`;

  return componentSource;
}

async function generatePublicApiSource(element: LitCustomElement) {
  const { name, tagNameWithoutPrefix } = element;
  const angularComponentName = name.replace('Element', 'Component');
  // Remove 'Kirby' prefix and keep 'Component' suffix for alias
  const aliasName = angularComponentName.replace(/^Kirby/, '');
  return `// AUTO-GENERATED - PLEASE DON'T EDIT THIS FILE MANUALLY.
    import { ${name} } from '${CORE_PACKAGE_JSON_NAME}/${tagNameWithoutPrefix}.element';
    export * from './${tagNameWithoutPrefix}.component';
    export { ${angularComponentName} as ${aliasName} } from './${tagNameWithoutPrefix}.component';
    ${name}.define();`;
}

async function formatWithEslint(unformattedSource: string, componentName: string) {
  const eslint = new ESLint({
    fix: true,
    cache: true,
    overrideConfigFile: path.resolve('tools/eslint-config/angular.json'),
  });
  const lintingResults = await eslint.lintText(unformattedSource, { filePath: 'component.ts' });

  if (lintingResults.length > 0 && lintingResults[0].output) {
    return lintingResults[0].output;
  }

  console.warn(`${componentName} Angular component source could not be formatted with ESLint.`);
  return unformattedSource;
}
