name: Bug report
description: Create a bug report
title: "[BUG]"
labels: [bug]
assignees: []

body:
  - type: textarea
    id: describe_the_bug
    attributes:
      label: Describe the bug and what you expected to happen
      placeholder: A clear and concise description of the bug and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Describe how to reproduce the bug
      description: >
        If possible, provide a minimal example or
        [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-6de5dek3?file=package.json)
        that we can use to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is your best bet on how severe the impact of this issue is? (The kirby team might change this, but your input is valuable)
      options:
        - (1) Critical — app crashes or critical user flow broken
        - (2) High — feature broken
        - (3) Medium — usable with workaround
        - (4) Low — minor issue
    validations:
      required: true

  - type: input
    id: kirby_version
    attributes:
      label: Which Kirby version was used?
      placeholder: e.g. v3.14.1
    validations:
      required: true

  - type: textarea
    id: attachments
    attributes:
      label: Add screenshots or videos
      description: |
        Drag and drop images or videos here, or paste them directly.
        You can also copy/paste screenshots into this field.
      placeholder: Paste or drop files here

  - type: input
    id: environment
    attributes:
      label: Environment (OS / Browser)
      description: Add any relevant environment details if applicable
      placeholder: e.g. macOS + Chrome 122, iOS + Safari, Windows + Edge

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other relevant information or context about the problem
      placeholder: e.g. Only happens after login, only on mobile, etc.
