import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { posix as path, resolve } from 'path';
import { ESLint } from 'eslint';
import * as ts from 'typescript';

const newLine = '\r\n';
const autoGeneratedFileHeader = `// AUTO-GENERATED - PLEASE DON'T EDIT THIS FILE MANUALLY`;
const startRegion = '// #region AUTO-GENERATED';
const endRegion = '// #endregion';

type PropertyMetaData = {
  name: string;
  type: string;
  optional: boolean;
  initializer: string | undefined;
  direction: 'Input' | 'Output' | undefined;
  bindingProperty: string | undefined;
};

type MethodMetaData = {
  name: string;
};

type ImportedName = {
  module: string;
  importName: string;
  localName: string;
};

type ComponentMetaData = {
  /** exportKey() of the original class, used to look up mocks of base classes */
  key: string;
  /** Public (exported) class name */
  className: string;
  /** Module specifier the class is publicly exported from, e.g. '@kirbydesign/designsystem/button' */
  importPath: string;
  decorator: string;
  selector: string;
  /** Type parameter list including brackets, e.g. '<TItem extends SegmentItem>', or '' */
  typeParameters: string;
  /** exportKey() of the extended class, if any */
  baseClassKey: string | undefined;
  properties: PropertyMetaData[];
  methods: MethodMetaData[];
  /** Imports needed for the types referenced by properties and type parameters */
  typeImports: ImportedName[];
  /** Referenced types that can't be imported, as they aren't part of any public API */
  unresolvedTypes: string[];
};

type MockFile = {
  fileName: string;
  components: ComponentMetaData[];
};

type MockReference = {
  mockClassName: string;
  fileName: string;
};

type OutputPaths = {
  base: string;
  jasmine: string;
  jest: string;
};

type EntryPoint = {
  importPath: string;
  entryFile: string;
  srcDir: string;
};

type PublicExport = {
  exportedName: string;
  importPath: string;
};

/** Keyed by `exportKey(absoluteDeclarationFile, declaredName)` */
type ExportMap = Map<string, PublicExport>;

type ExportedClass = PublicExport & {
  key: string;
  declaration: ts.ClassDeclaration;
};

type ClassReference = {
  key: string;
  name: string;
};

const exportKey = (fileName: string, declaredName: string) =>
  `${resolve(fileName)}#${declaredName}`;

// ng-packagr's default when ng-package.json doesn't specify lib.entryFile:
const defaultEntryFile = 'src/public_api.ts';

const isIgnoredFolder = (name: string) =>
  name === 'node_modules' || name === 'dist' || name.startsWith('.') || name.startsWith('testing');

/** Collects named imports grouped by module, de-duplicated by local name */
class ImportCollector {
  private modules = new Map<string, Map<string, string>>(); // module -> localName -> importName

  add(module: string, importName: string, localName = importName) {
    if (this.has(localName)) return;
    if (!this.modules.has(module)) this.modules.set(module, new Map());
    this.modules.get(module)!.set(localName, importName);
  }

  has(localName: string) {
    return Array.from(this.modules.values()).some((names) => names.has(localName));
  }

  render(): string[] {
    // Groups, separated by a blank line: angular + third party, kirby, relative
    const rank = (module: string) =>
      module.startsWith('@angular/')
        ? 0
        : module.startsWith('.')
          ? 3
          : module.includes('kirbydesign/designsystem')
            ? 2
            : 1;
    const group = (module: string) => Math.max(rank(module) - 1, 0);
    const sorted = Array.from(this.modules.entries()).sort(
      ([a], [b]) => rank(a) - rank(b) || a.localeCompare(b)
    );
    return sorted.map(([module, names], index) => {
      const specifiers = Array.from(names.entries())
        .map(([localName, importName]) =>
          localName === importName ? localName : `${importName} as ${localName}`
        )
        .sort();
      const isNewGroup = index > 0 && group(sorted[index - 1][0]) !== group(module);
      return `${isNewGroup ? newLine : ''}import { ${specifiers.join(', ')} } from '${module}';`;
    });
  }
}

export class GenerateMocks {
  private program!: ts.Program;
  private checker!: ts.TypeChecker;
  private exportMap!: ExportMap;
  private exportedClasses: ExportedClass[] = [];
  private warnings: string[] = [];

  /**
   * Generates mocks for all components, directives and providers exported from the
   * entry points of the library.
   */
  async renderMocks(libRoot: string, outputPaths: OutputPaths) {
    const outputPath = path.normalize(outputPaths.base);
    const packageName: string = JSON.parse(
      readFileSync(path.join(libRoot, 'package.json'), 'utf8')
    ).name;
    const entryPoints = this.findEntryPoints(libRoot, packageName);
    this.createProgram(entryPoints);
    this.exportMap = this.getPublicExports(entryPoints);

    const mockFiles: MockFile[] = [];
    const providers: ComponentMetaData[] = [];
    for (const entryPoint of entryPoints) {
      this.collect(entryPoint.srcDir, outputPath, mockFiles, providers);
    }

    const mocks = new Map<string, MockReference>();
    mockFiles.forEach((mockFile) =>
      mockFile.components.forEach((metaData) =>
        mocks.set(metaData.key, {
          mockClassName: 'Mock' + metaData.className,
          fileName: mockFile.fileName,
        })
      )
    );

    await Promise.all([
      ...mockFiles.map((mockFile) => this.renderMock(mockFile, mocks)),
      this.renderMockComponentDeclaration(mockFiles, outputPath),
      this.renderMockComponentsBarrel(mockFiles, outputPath),
      this.renderKirbyImports(mockFiles, outputPath),
      this.renderMockProviders(providers, path.normalize(outputPaths.jasmine), 'jasmine'),
      this.renderMockProviders(providers, path.normalize(outputPaths.jest), 'jest'),
    ]);

    if (this.warnings.length) {
      console.warn(
        `generate-mocks finished with ${this.warnings.length} warning(s):${newLine}` +
          this.warnings.map((warning) => `  - ${warning}`).join(newLine)
      );
    }
  }

  private findEntryPoints(libRoot: string, packageName: string): EntryPoint[] {
    const entryPoints: EntryPoint[] = [];
    const primaryEntryFile = this.getEntryFile(libRoot);
    if (primaryEntryFile) {
      entryPoints.push({
        importPath: packageName,
        entryFile: primaryEntryFile,
        srcDir: path.dirname(primaryEntryFile),
      });
    }
    const visit = (dir: string) => {
      for (const dirent of readdirSync(dir, { withFileTypes: true })) {
        if (!dirent.isDirectory() || isIgnoredFolder(dirent.name)) continue;
        const subDir = path.join(dir, dirent.name);
        const entryFile = this.getEntryFile(subDir);
        if (entryFile) {
          entryPoints.push({
            importPath: `${packageName}/${path.relative(libRoot, subDir)}`,
            entryFile,
            srcDir: path.dirname(entryFile),
          });
        }
        visit(subDir);
      }
    };
    visit(libRoot);
    return entryPoints.sort((a, b) => a.importPath.localeCompare(b.importPath));
  }

  private getEntryFile(dir: string): string | undefined {
    const ngPackageFile = path.join(dir, 'ng-package.json');
    if (!existsSync(ngPackageFile)) return undefined;
    const ngPackage = JSON.parse(readFileSync(ngPackageFile, 'utf8'));
    const entryFile = path.join(dir, ngPackage.lib?.entryFile ?? defaultEntryFile);
    if (!existsSync(entryFile)) {
      throw new Error(`Entry file not found for ${ngPackageFile}: ${entryFile}`);
    }
    return entryFile;
  }

  /**
   * Creates a program spanning all entry points, with the library's own module specifiers
   * mapped to source, so types can be traced back to the entry point that declares them.
   */
  private createProgram(entryPoints: EntryPoint[]) {
    const paths: ts.MapLike<string[]> = {};
    entryPoints.forEach((entryPoint) => {
      paths[entryPoint.importPath] = [resolve(entryPoint.entryFile)];
    });
    this.program = ts.createProgram(
      entryPoints.map((entryPoint) => resolve(entryPoint.entryFile)),
      {
        noEmit: true,
        skipLibCheck: true,
        types: [],
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.ESNext,
        moduleResolution: ts.ModuleResolutionKind.Bundler,
        experimentalDecorators: true,
        baseUrl: resolve('.'),
        paths,
      }
    );
    this.checker = this.program.getTypeChecker();
  }

  /**
   * Resolves the public API of every entry point (following `export *`, re-export chains
   * and `as` aliases) and maps each exported declaration to its public name and the
   * entry point it is exported from.
   */
  private getPublicExports(entryPoints: EntryPoint[]): ExportMap {
    const exportMap: ExportMap = new Map();
    for (const entryPoint of entryPoints) {
      const sourceFile = this.program.getSourceFile(resolve(entryPoint.entryFile));
      const moduleSymbol = sourceFile && this.checker.getSymbolAtLocation(sourceFile);
      if (!moduleSymbol) {
        throw new Error(`Could not resolve exports of entry file: ${entryPoint.entryFile}`);
      }
      const srcDir = resolve(entryPoint.srcDir) + '/';
      for (const exported of this.checker.getExportsOfModule(moduleSymbol)) {
        const target = this.resolveAlias(exported);
        for (const declaration of target.declarations ?? []) {
          const fileName = declaration.getSourceFile().fileName;
          // Only attribute declarations to the entry point that declares them, not ones re-exporting them:
          if (!resolve(fileName).startsWith(srcDir)) continue;
          const publicExport = { exportedName: exported.name, importPath: entryPoint.importPath };
          exportMap.set(exportKey(fileName, target.name), publicExport);
          if (ts.isClassDeclaration(declaration)) {
            this.exportedClasses.push({
              ...publicExport,
              key: exportKey(fileName, target.name),
              declaration,
            });
          }
        }
      }
    }
    return exportMap;
  }

  private resolveAlias(symbol: ts.Symbol) {
    return symbol.flags & ts.SymbolFlags.Alias ? this.checker.getAliasedSymbol(symbol) : symbol;
  }

  private getPublicExport(declaration: ts.Declaration, declaredName: string) {
    return this.exportMap.get(exportKey(declaration.getSourceFile().fileName, declaredName));
  }

  private collect(
    folderpath: string,
    outputPath: string,
    mockFiles: MockFile[],
    providers: ComponentMetaData[]
  ) {
    for (const fileOrFolder of readdirSync(folderpath)) {
      const fullPath = path.join(folderpath, fileOrFolder);
      if (statSync(fullPath).isDirectory()) {
        // Nested entry points are collected on their own:
        if (existsSync(path.join(fullPath, 'ng-package.json'))) continue;
        this.collect(fullPath, outputPath, mockFiles, providers);
        continue;
      }
      if (fileOrFolder.endsWith('.component.ts')) {
        const components = this.generateMetaData(fullPath).filter(
          (metaData) => metaData.decorator === 'Component' || metaData.decorator === 'Directive'
        );
        if (!components.length) continue;
        const fileName = path.join(outputPath, 'components', 'mock.' + fileOrFolder);
        if (mockFiles.some((mockFile) => mockFile.fileName === fileName)) {
          throw new Error(
            `Mock file name collision: ${fileName} (from ${fullPath}). Component file names must be unique across entry points.`
          );
        }
        mockFiles.push({ fileName, components });
      }
      if (fileOrFolder.endsWith('.controller.ts') || fileOrFolder.endsWith('.service.ts')) {
        providers.push(
          ...this.generateMetaData(fullPath).filter(
            (metaData) => metaData.decorator === 'Injectable' && metaData.methods.length
          )
        );
      }
    }
  }

  /**
   * Renders KIRBY_IMPORTS: the Kirby components, directives and NgModules that can safely be
   * swapped for KirbyTestingBaseModule in the imports of a standalone component under test.
   *
   * NgModules are only included if everything they export has a mock (directly or through
   * other included modules), as removing them would otherwise break the consumer's template.
   */
  private renderKirbyImports(mockFiles: MockFile[], outputPath: string) {
    const handWrittenDirectiveMocks = this.getHandWrittenMockClassNames(
      path.join(outputPath, 'directives')
    );
    const mocked = new Map<string, PublicExport>();
    mockFiles.forEach((mockFile) =>
      mockFile.components.forEach(({ key, className, importPath }) =>
        mocked.set(key, { exportedName: className, importPath })
      )
    );
    this.exportedClasses
      .filter(
        (exportedClass) =>
          this.getDecoratorName(exportedClass.declaration) === 'Directive' &&
          handWrittenDirectiveMocks.has('Mock' + exportedClass.exportedName)
      )
      .forEach(({ key, exportedName, importPath }) =>
        mocked.set(key, { exportedName, importPath })
      );

    const modules = this.exportedClasses
      .filter((exportedClass) => this.getDecoratorName(exportedClass.declaration) === 'NgModule')
      .map((module) => ({ ...module, exports: this.getNgModuleExports(module.declaration) }));
    // Modules can export other modules, so keep adding modules until nothing changes:
    let added = true;
    while (added) {
      added = false;
      for (const module of modules) {
        if (mocked.has(module.key)) continue;
        if (module.exports.every((exported) => exported && mocked.has(exported.key))) {
          mocked.set(module.key, module);
          added = true;
        }
      }
    }
    modules
      .filter((module) => !mocked.has(module.key))
      .forEach((module) => {
        const uncovered = module.exports
          .map((exported, index) => exported?.name ?? `<unresolved export #${index}>`)
          .filter((name, index) => !mocked.has(module.exports[index]?.key ?? ''));
        this.warnings.push(
          `${module.exportedName} is not swapped for mocks in standalone tests, as it exports something without a mock: ${uncovered.join(', ')}`
        );
      });

    const imports = new ImportCollector();
    imports.add('@angular/core', 'Type');
    const entries = Array.from(mocked.values()).sort(
      (a, b) =>
        a.importPath.localeCompare(b.importPath) || a.exportedName.localeCompare(b.exportedName)
    );
    entries.forEach(({ exportedName, importPath }) => imports.add(importPath, exportedName));
    const content = `${autoGeneratedFileHeader}

${imports.render().join(newLine)}

/**
 * Kirby components, directives and modules that have mocks in KirbyTestingBaseModule,
 * i.e. what can be removed from the imports of a standalone component under test.
 */
export const KIRBY_IMPORTS: Type<unknown>[] = [
  ${entries.map(({ exportedName }) => exportedName).join(`,${newLine}  `)},
];
`;
    return this.saveFileLinted(path.join(outputPath, 'kirby-imports.ts'), content);
  }

  private getHandWrittenMockClassNames(folderpath: string) {
    const classNames = new Set<string>();
    if (!existsSync(folderpath)) return classNames;
    readdirSync(folderpath)
      .filter((fileName) => fileName.startsWith('mock.') && fileName.endsWith('.ts'))
      .forEach((fileName) => {
        const content = readFileSync(path.join(folderpath, fileName), 'utf8');
        for (const match of content.matchAll(/export class (Mock\w+)/g)) {
          classNames.add(match[1]);
        }
      });
    return classNames;
  }

  private getDecoratorName(classDeclaration: ts.ClassDeclaration) {
    for (const decorator of ts.getDecorators(classDeclaration) ?? []) {
      if (
        ts.isCallExpression(decorator.expression) &&
        ts.isIdentifier(decorator.expression.expression)
      ) {
        return decorator.expression.expression.text;
      }
    }
    return undefined;
  }

  /** Resolves the classes in the `exports` of an NgModule; undefined entries couldn't be resolved */
  private getNgModuleExports(classDeclaration: ts.ClassDeclaration) {
    const exports: (ClassReference | undefined)[] = [];
    const decorator = ts.getDecorators(classDeclaration)?.[0];
    const decoratorArg =
      decorator && ts.isCallExpression(decorator.expression)
        ? decorator.expression.arguments[0]
        : undefined;
    if (!decoratorArg || !ts.isObjectLiteralExpression(decoratorArg)) return exports;
    const exportsProp = decoratorArg.properties.find((prop) => prop.name?.getText() === 'exports');
    if (exportsProp && ts.isPropertyAssignment(exportsProp)) {
      this.resolveClassReferences(exportsProp.initializer, exports);
    }
    return exports;
  }

  private resolveClassReferences(node: ts.Expression, result: (ClassReference | undefined)[]) {
    if (ts.isArrayLiteralExpression(node)) {
      node.elements.forEach((element) => this.resolveClassReferences(element, result));
      return;
    }
    if (ts.isSpreadElement(node)) {
      this.resolveClassReferences(node.expression, result);
      return;
    }
    if (ts.isIdentifier(node)) {
      const symbol = this.checker.getSymbolAtLocation(node);
      const target = symbol && this.resolveAlias(symbol);
      const declaration = target?.declarations?.[0];
      if (target && declaration && ts.isClassDeclaration(declaration)) {
        result.push({
          key: exportKey(declaration.getSourceFile().fileName, target.name),
          name: node.text,
        });
        return;
      }
      if (declaration && ts.isVariableDeclaration(declaration) && declaration.initializer) {
        this.resolveClassReferences(declaration.initializer, result);
        return;
      }
    }
    result.push(undefined);
  }

  /** Renders the barrel file re-exporting all mock components, e.g. components/index.ts */
  private renderMockComponentsBarrel(mockFiles: MockFile[], outputPath: string) {
    const componentsPath = path.join(outputPath, 'components');
    const exports = mockFiles
      .map((mockFile) => {
        const classNames = mockFile.components.map((metaData) => 'Mock' + metaData.className);
        const relativePath = './' + path.relative(componentsPath, mockFile.fileName);
        return `export { ${classNames.join(', ')} } from '${relativePath.replace(/\.ts$/, '')}';`;
      })
      .join(newLine);
    const content = `${autoGeneratedFileHeader}

${exports}
`;
    return this.saveFileLinted(path.join(componentsPath, 'index.ts'), content);
  }

  private renderMockComponentDeclaration(mockFiles: MockFile[], outputPath: string) {
    const imports = mockFiles
      .map((mockFile) => {
        const classNames = mockFile.components.map((metaData) => 'Mock' + metaData.className);
        const relativePath = mockFile.fileName.replace(outputPath, './').replace('.ts', '');
        return `import { ${classNames.join(', ')} } from '${relativePath}';`;
      })
      .join(newLine);
    const components = mockFiles
      .map((mockFile) =>
        mockFile.components.map((metaData) => 'Mock' + metaData.className).join(`,${newLine}  `)
      )
      .join(`,${newLine}  `);
    const filename = path.join(outputPath, '/mock-components.ts');
    const content = `${autoGeneratedFileHeader}

${imports}

export const MOCK_COMPONENTS = [
  ${components},
];
`;
    return this.saveFileLinted(filename, content);
  }

  private renderMockProviders(
    exportedProviders: ComponentMetaData[],
    outputPath: string,
    testFramework: 'jasmine' | 'jest'
  ) {
    const imports = new ImportCollector();
    exportedProviders.forEach((provider) => imports.add(provider.importPath, provider.className));
    const hasObservableProperties = exportedProviders.some((provider) =>
      provider.properties.some((p) => p.type === 'Observable')
    );
    if (hasObservableProperties) {
      imports.add('rxjs', 'EMPTY');
    }
    const importStatements = imports.render().join(newLine);
    const mockProviderFactoryRenderer =
      testFramework === 'jasmine'
        ? this.renderJasmineMockProviderFactory.bind(this)
        : this.renderJestMockProviderFactory.bind(this);

    const factories = exportedProviders.map(mockProviderFactoryRenderer).join(newLine + newLine);
    const providers = exportedProviders
      .map(
        (provider) =>
          `{
  provide: ${provider.className},
  useFactory: ${this.getMockProviderFactoryName(provider.className)}
}`
      )
      .join(`,${newLine}  `);
    const filename = path.join(outputPath, '/mock-providers.ts');
    const content = `${autoGeneratedFileHeader}

    ${importStatements}

    ${factories}

export const MOCK_PROVIDERS = [
${providers},
];
`;
    return this.saveFileLinted(filename, content);
  }

  private renderJasmineMockProviderFactory(componentMetaData: ComponentMetaData) {
    const methodNames = componentMetaData.methods.map((m) => `'${m.name}'`).join(',' + newLine);
    const methodNamesArray = `[${methodNames}]`;
    const observableProperties = this.getObservableProperties(componentMetaData).join(
      ',' + newLine
    );
    const propertyNamesObject = observableProperties.length ? `, { ${observableProperties} }` : '';
    const funcName = this.getMockProviderFactoryName(componentMetaData.className);
    return `export function ${funcName}() {
  return jasmine.createSpyObj<${componentMetaData.className}>('${componentMetaData.className}', ${methodNamesArray}${propertyNamesObject}
  );
}`;
  }

  private renderJestMockProviderFactory(componentMetaData: ComponentMetaData) {
    const mockMethods = componentMetaData.methods.map((m) => `${m.name}: jest.fn()`);
    const observableProperties = this.getObservableProperties(componentMetaData);
    const members = mockMethods.concat(observableProperties).join(',' + newLine);
    const funcName = this.getMockProviderFactoryName(componentMetaData.className);
    return `export function ${funcName}() {
  return {
    ${members}
  };
}`;
  }

  private getObservableProperties(componentMetaData: ComponentMetaData) {
    return componentMetaData.properties
      .filter((p) => p.type === 'Observable')
      .map((p) => `${p.name}: EMPTY`); // Ensure observable properties can be subscribed, see: https://ng-mocks.sudo.eu/extra/mock-observables
  }

  private getMockProviderFactoryName(className: string) {
    return className[0].toLowerCase() + className.slice(1) + 'Factory';
  }

  private renderMock(mockFile: MockFile, mocks: Map<string, MockReference>) {
    const { fileName, components } = mockFile;
    const imports = new ImportCollector();
    this.addAngularImports(imports, components);
    components.forEach((metaData) => {
      imports.add(metaData.importPath, metaData.className);
      metaData.typeImports.forEach(({ module, importName, localName }) =>
        imports.add(module, importName, localName)
      );
    });

    const rendered = components.map((metaData) => {
      const baseMock = metaData.baseClassKey ? mocks.get(metaData.baseClassKey) : undefined;
      if (baseMock && baseMock.fileName !== fileName) {
        const relativePath = path.relative(path.dirname(fileName), baseMock.fileName);
        imports.add('./' + relativePath.replace(/\.ts$/, ''), baseMock.mockClassName);
      }
      return this.renderClass(metaData, baseMock?.mockClassName);
    });

    const autoGeneratedContent = `${startRegion} - PLEASE DON'T EDIT CONTENT WITHIN!
${rendered.join(newLine)}
${endRegion}
`;
    let handWrittenContent = '';
    if (existsSync(fileName)) {
      const existingContent = readFileSync(fileName).toString();
      const regionStartIndex = existingContent.indexOf(startRegion);
      handWrittenContent = this.mergeHandWrittenContent(
        existingContent.substring(0, Math.max(regionStartIndex, 0)),
        imports,
        autoGeneratedContent
      );
    }
    components.forEach((metaData) =>
      new Set(metaData.unresolvedTypes).forEach((typeName) => {
        const isDeclared = new RegExp(`\\b(type|interface|class|enum)\\s+${typeName}\\b`);
        if (!isDeclared.test(handWrittenContent)) {
          this.warnings.push(
            `Mock${metaData.className}: type '${typeName}' is not exported from any entry point. Declare it in ${fileName}, above the auto-generated region.`
          );
        }
      })
    );
    const content =
      imports.render().join(newLine) +
      newLine +
      newLine +
      handWrittenContent +
      autoGeneratedContent;
    return this.saveFileLinted(fileName, content);
  }

  private mergeHandWrittenContent(
    existingHeader: string,
    imports: ImportCollector,
    autoGeneratedContent: string
  ) {
    const sourceFile = ts.createSourceFile(
      'header.ts',
      existingHeader,
      ts.ScriptTarget.ES2022,
      true
    );
    const namedImports: ImportedName[] = [];
    let otherContent = '';
    for (const statement of sourceFile.statements) {
      const importClause = ts.isImportDeclaration(statement) ? statement.importClause : undefined;
      const namedBindings = importClause?.namedBindings;
      if (importClause && !importClause.name && namedBindings && ts.isNamedImports(namedBindings)) {
        const module = (statement as ts.ImportDeclaration).moduleSpecifier as ts.StringLiteral;
        namedBindings.elements.forEach((element) =>
          namedImports.push({
            module: module.text,
            importName: (element.propertyName ?? element.name).text,
            localName: element.name.text,
          })
        );
        // Keep comments attached to the import (the import itself is regenerated):
        const leadingComments = statement
          .getFullText(sourceFile)
          .slice(0, statement.getStart(sourceFile) - statement.getFullStart())
          .trim();
        if (leadingComments) otherContent += newLine + leadingComments + newLine;
      } else {
        otherContent += statement.getFullText(sourceFile);
      }
    }
    otherContent = (otherContent + sourceFile.endOfFileToken.getFullText(sourceFile)).trim();
    const code = otherContent + newLine + autoGeneratedContent;
    namedImports
      .filter(({ localName }) => new RegExp(`\\b${localName}\\b`).test(code))
      .forEach(({ module, importName, localName }) => imports.add(module, importName, localName));
    return otherContent ? otherContent + newLine + newLine : '';
  }

  private renderClass(componentMetaData: ComponentMetaData, baseMockClassName?: string): string {
    const { className, typeParameters } = componentMetaData;
    const mockClassName = 'Mock' + className;
    const propertiesString = this.renderProperties(componentMetaData.properties);
    const methodsString = this.renderMethods(componentMetaData.methods);
    const validSelector =
      componentMetaData.selector &&
      (componentMetaData.selector.startsWith(`'kirby`) ||
        componentMetaData.selector.startsWith(`'[kirby`));
    const esLintDisableSelector =
      componentMetaData.selector && !validSelector
        ? `${newLine}  // eslint-disable-next-line @angular-eslint/component-selector`
        : '';
    const selector = componentMetaData.selector
      ? `${esLintDisableSelector}${newLine}  selector: ${componentMetaData.selector},`
      : '';
    const isComponent = componentMetaData.decorator === 'Component';
    const template = isComponent ? `${newLine}  template: '<ng-content></ng-content>',` : '';
    // Unique host attribute makes Angular generate a component ID distinct from the real component:
    const host = isComponent ? `${newLine}  host: { mock: 'mock' },` : '';
    const providers = `
providers: [
    {
      provide: ${className},
      useExisting: forwardRef(() => ${mockClassName}),
    },
  ],
`;
    const extendsClause = baseMockClassName ? ` extends ${baseMockClassName}` : '';

    const config = `{${selector}${template}${host}${providers}}`;
    const content = `@${componentMetaData.decorator}(${config})
export class ${mockClassName}${typeParameters}${extendsClause} {${propertiesString}${methodsString}}
`;
    return content;
  }

  private addAngularImports(imports: ImportCollector, components: ComponentMetaData[]) {
    const hasDecoratedType = (type: string) =>
      components.some((metaData) => metaData.decorator === type);
    const hasDirection = (direction: string) =>
      components.some((metaData) => metaData.properties.some((p) => p.direction === direction));
    const angularCoreImports = [
      ...(hasDecoratedType('Component') || hasDecoratedType('Directive') ? ['forwardRef'] : []),
      ...(hasDecoratedType('Component') ? ['Component'] : []),
      ...(hasDecoratedType('Directive') ? ['Directive'] : []),
      ...(hasDirection('Input') ? ['Input'] : []),
      ...(hasDirection('Output') ? ['Output', 'EventEmitter'] : []),
    ];
    angularCoreImports.forEach((name) => imports.add('@angular/core', name));
  }

  private renderProperties(properties: PropertyMetaData[]) {
    const renderedProps = properties.map((prop) => {
      switch (prop.direction) {
        case 'Input': {
          const optional = prop.optional ? '?' : '';
          const typeDeclaration = prop.type ? `: ${prop.type}` : '';
          const bindingProperty = prop.bindingProperty || '';
          return `@Input(${bindingProperty}) ${prop.name}${optional}${typeDeclaration};`;
        }
        case 'Output':
          return `@Output() ${prop.name} = ${prop.initializer};`;
      }
    });
    const separator = `${newLine}  `;
    return renderedProps.length ? separator + renderedProps.join(separator) + newLine : '';
  }

  private renderMethods(methods: MethodMetaData[]) {
    const renderedMethods = methods.map((method) => {
      return `${method.name}() {${newLine}    // NOOP${newLine}  }`;
    });
    const separator = `${newLine}  `;
    return renderedMethods.length
      ? newLine + separator + renderedMethods.join(separator) + newLine
      : '';
  }

  /** Returns metadata for the decorated classes in fileName that are part of a public API */
  private generateMetaData(fileName: string) {
    const sourceFile = this.program.getSourceFile(resolve(fileName));
    const components: ComponentMetaData[] = [];
    if (!sourceFile) {
      // Not reachable from any entry point, i.e. not part of a public API
      return components;
    }
    sourceFile.forEachChild((node) => {
      if (!ts.isClassDeclaration(node) || !node.name) return;
      const publicExport = this.getPublicExport(node, node.name.text);
      if (!publicExport) return;
      const componentMetaData: ComponentMetaData = {
        key: exportKey(fileName, node.name.text),
        className: publicExport.exportedName,
        importPath: publicExport.importPath,
        decorator: '',
        selector: '',
        typeParameters: '',
        baseClassKey: undefined,
        properties: [],
        methods: [],
        typeImports: [],
        unresolvedTypes: [],
      };
      this.visitClassDeclaration(node, componentMetaData);
      if (!componentMetaData.decorator) return;
      node.members.forEach((member) => {
        if (
          ts.isPropertyDeclaration(member) ||
          ts.isSetAccessorDeclaration(member) ||
          ts.isGetAccessorDeclaration(member)
        ) {
          this.visitPropertyDeclaration(member, componentMetaData);
        }
        if (ts.isMethodDeclaration(member)) {
          this.visitMethodDeclaration(member, componentMetaData);
        }
      });
      components.push(componentMetaData);
    });
    return components;
  }

  private visitClassDeclaration(
    classDeclaration: ts.ClassDeclaration,
    componentMetaData: ComponentMetaData
  ) {
    ts.getDecorators(classDeclaration)?.forEach((decorator) => {
      if (!ts.isCallExpression(decorator.expression)) return;
      if (!ts.isIdentifier(decorator.expression.expression)) return;
      const decoratorName = decorator.expression.expression.getText();
      if (
        decoratorName === 'Component' ||
        decoratorName === 'Directive' ||
        decoratorName === 'Injectable'
      ) {
        componentMetaData.decorator = decoratorName;
        const decoratorArg = decorator.expression.arguments[0];
        if (decoratorArg && ts.isObjectLiteralExpression(decoratorArg)) {
          const selectorProp = decoratorArg.properties.find(
            (prop) => prop.name?.getText() === 'selector'
          );
          if (selectorProp && ts.isPropertyAssignment(selectorProp)) {
            componentMetaData.selector = selectorProp.initializer.getText();
          }
        }
      }
    });

    if (classDeclaration.typeParameters) {
      componentMetaData.typeParameters = `<${classDeclaration.typeParameters
        .map((typeParameter) => typeParameter.getText())
        .join(', ')}>`;
      classDeclaration.typeParameters.forEach((typeParameter) =>
        this.collectTypeImports(typeParameter, componentMetaData)
      );
    }

    const baseClass = classDeclaration.heritageClauses?.find(
      (clause) => clause.token === ts.SyntaxKind.ExtendsKeyword
    )?.types[0]?.expression;
    if (baseClass && ts.isIdentifier(baseClass)) {
      const symbol = this.checker.getSymbolAtLocation(baseClass);
      const target = symbol && this.resolveAlias(symbol);
      const declaration = target?.declarations?.[0];
      if (target && declaration) {
        componentMetaData.baseClassKey = exportKey(
          declaration.getSourceFile().fileName,
          target.name
        );
      }
    }
  }

  /**
   * Only members explicitly marked as `public` are part of the mocked API. This is an opt-in
   * convention, so internal (implicitly public) members like template handlers aren't mocked.
   */
  private isExplicitlyPublic(member: ts.ClassElement) {
    const modifiers = ts.canHaveModifiers(member) ? ts.getModifiers(member) : undefined;
    return (
      !!modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.PublicKeyword) &&
      !modifiers.some((modifier) => modifier.kind === ts.SyntaxKind.StaticKeyword)
    );
  }

  private visitPropertyDeclaration(
    propertyDeclaration:
      | ts.SetAccessorDeclaration
      | ts.GetAccessorDeclaration
      | ts.PropertyDeclaration,
    componentMetaData: ComponentMetaData
  ) {
    const inputOutputDecorator = this.getInputOutputDecorator(propertyDeclaration);
    if (componentMetaData.decorator === 'Injectable') {
      if (!this.isExplicitlyPublic(propertyDeclaration)) return;
    } else if (!inputOutputDecorator.type) {
      // Only render Input/Output properties for components and directives:
      return;
    }

    const name = propertyDeclaration.name.getText();
    if (componentMetaData.properties.some((prop) => prop.name === name)) return;
    const type = this.getPropertyType(name, propertyDeclaration, componentMetaData);
    const typeNode = this.getPropertyTypeNode(propertyDeclaration);
    if (typeNode) {
      this.collectTypeImports(typeNode, componentMetaData);
    }
    let initializer: string | undefined;
    if (ts.isPropertyDeclaration(propertyDeclaration) && propertyDeclaration.initializer) {
      initializer = propertyDeclaration.initializer.getText();
      if (inputOutputDecorator.type === 'Output') {
        // e.g. new EventEmitter<SomeType>()
        this.collectTypeImports(propertyDeclaration.initializer, componentMetaData);
      }
    }
    componentMetaData.properties.push({
      name,
      type,
      optional:
        ts.isPropertyDeclaration(propertyDeclaration) && !!propertyDeclaration.questionToken,
      initializer,
      direction: inputOutputDecorator.type,
      bindingProperty: inputOutputDecorator.bindingProperty,
    });
  }

  private visitMethodDeclaration(
    methodDeclaration: ts.MethodDeclaration,
    componentMetaData: ComponentMetaData
  ) {
    if (!this.isExplicitlyPublic(methodDeclaration)) return;
    const name = methodDeclaration.name.getText();
    if (name.startsWith('ng') || name.startsWith('_')) return;
    // Skip overloads:
    if (componentMetaData.methods.some((method) => method.name === name)) return;
    componentMetaData.methods.push({ name });
  }

  /** Adds imports for all types referenced within node */
  private collectTypeImports(node: ts.Node, componentMetaData: ComponentMetaData) {
    const visit = (child: ts.Node) => {
      let identifier: ts.EntityName | undefined;
      if (ts.isTypeReferenceNode(child)) identifier = child.typeName;
      if (ts.isTypeQueryNode(child)) identifier = child.exprName;
      while (identifier && ts.isQualifiedName(identifier)) identifier = identifier.left;
      if (identifier && ts.isIdentifier(identifier)) {
        const typeImport = this.resolveTypeImport(identifier, componentMetaData);
        if (typeImport) componentMetaData.typeImports.push(typeImport);
      }
      ts.forEachChild(child, visit);
    };
    visit(node);
  }

  private resolveTypeImport(
    identifier: ts.Identifier,
    componentMetaData: ComponentMetaData
  ): ImportedName | undefined {
    const localName = identifier.text;
    const symbol = this.checker.getSymbolAtLocation(identifier);
    if (!symbol) return undefined;
    const target = this.resolveAlias(symbol);
    const declaration = target.declarations?.[0];
    if (declaration && ts.isTypeParameterDeclaration(declaration)) return undefined;

    // Prefer the secondary entry point that publicly exports the type:
    const publicExport = declaration && this.getPublicExport(declaration, target.name);
    if (publicExport) {
      return { module: publicExport.importPath, importName: publicExport.exportedName, localName };
    }

    if (symbol.flags & ts.SymbolFlags.Alias) {
      // Imported from outside the library, e.g. '@angular/core' or '@kirbydesign/core':
      const importSpecifier = symbol.declarations?.find(ts.isImportSpecifier);
      const moduleSpecifier = importSpecifier?.parent.parent.parent.moduleSpecifier;
      if (importSpecifier && moduleSpecifier && ts.isStringLiteral(moduleSpecifier)) {
        if (!moduleSpecifier.text.startsWith('.')) {
          return {
            module: moduleSpecifier.text,
            importName: (importSpecifier.propertyName ?? importSpecifier.name).text,
            localName,
          };
        }
      }
    } else if (!declaration || declaration.getSourceFile().isDeclarationFile) {
      // Global type, e.g. Date or HTMLElement
      return undefined;
    }

    componentMetaData.unresolvedTypes.push(localName);
    return undefined;
  }

  private getInputOutputDecorator(
    propertyDeclaration:
      | ts.SetAccessorDeclaration
      | ts.GetAccessorDeclaration
      | ts.PropertyDeclaration
  ): { type: 'Input' | 'Output' | undefined; bindingProperty: string | undefined } {
    const inputOutputDecorator: {
      type: 'Input' | 'Output' | undefined;
      bindingProperty: string | undefined;
    } = { type: undefined, bindingProperty: undefined };
    ts.getDecorators(propertyDeclaration)?.forEach((decorator) => {
      if (!ts.isCallExpression(decorator.expression)) return;
      if (!ts.isIdentifier(decorator.expression.expression)) return;
      const decoratorName = decorator.expression.expression.getText();
      if (decoratorName === 'Input' || decoratorName === 'Output') {
        inputOutputDecorator.type = decoratorName;
        const bindingPropertyArg = decorator.expression.arguments[0];
        if (bindingPropertyArg && ts.isStringLiteral(bindingPropertyArg)) {
          inputOutputDecorator.bindingProperty = bindingPropertyArg.getText();
        }
      }
    });
    return inputOutputDecorator;
  }

  private getPropertyTypeNode(
    propertyDeclaration:
      | ts.PropertyDeclaration
      | ts.SetAccessorDeclaration
      | ts.GetAccessorDeclaration
  ): ts.TypeNode | undefined {
    if (ts.isSetAccessorDeclaration(propertyDeclaration)) {
      return propertyDeclaration.parameters[0]?.type;
    }
    return propertyDeclaration.type;
  }

  private getPropertyType(
    propertyName: string,
    propertyDeclaration:
      | ts.PropertyDeclaration
      | ts.SetAccessorDeclaration
      | ts.GetAccessorDeclaration,
    componentMetaData: ComponentMetaData
  ): string {
    if (ts.isPropertyDeclaration(propertyDeclaration)) {
      return this.getPropertyTypeFromPropertyDeclaration(
        propertyName,
        propertyDeclaration,
        componentMetaData
      );
    }
    const type = this.getPropertyTypeNode(propertyDeclaration)?.getText() ?? '';
    if (!type) {
      console.warn(
        `Can't infer type for property '${componentMetaData.className}.${propertyName}' from:`,
        propertyDeclaration.getText()
      );
    }
    return type;
  }

  private getPropertyTypeFromPropertyDeclaration(
    propertyName: string,
    propertyDeclaration: ts.PropertyDeclaration,
    componentMetaData: ComponentMetaData
  ): string {
    let inferredType = '';
    if (!propertyDeclaration.type && propertyDeclaration.initializer) {
      switch (propertyDeclaration.initializer.kind) {
        case ts.SyntaxKind.FalseKeyword:
        case ts.SyntaxKind.TrueKeyword: {
          inferredType = 'boolean';
          break;
        }
        case ts.SyntaxKind.NumericLiteral: {
          inferredType = 'number';
          break;
        }
        case ts.SyntaxKind.StringLiteral: {
          inferredType = 'string';
          break;
        }
        case ts.SyntaxKind.ArrayLiteralExpression: {
          inferredType = '[]';
          break;
        }
        default: {
          const propInitializer = propertyDeclaration.initializer.getText();
          if (propInitializer.startsWith('new EventEmitter')) {
            inferredType = 'EventEmitter';
            break;
          }
          if (
            propInitializer.match(
              /\.asObservable\(\)|^of\(|new (?:Observable|Subject|ReplaySubject)\(/
            )
          ) {
            inferredType = 'Observable';
            break;
          }
          console.warn(
            `Can't infer type for property '${componentMetaData.className}.${propertyName}':`,
            ts.SyntaxKind[propertyDeclaration.initializer.kind],
            `(${propertyDeclaration.initializer.kind})`
          );
        }
      }
    }
    return propertyDeclaration.type ? propertyDeclaration.type.getText() : inferredType;
  }

  private async saveFileLinted(filename: string, content: string) {
    // Always write the raw content first; ESLint only writes files it actually fixed:
    writeFileSync(filename, content);
    const linter = new ESLint({ fix: true });
    const result = await linter.lintText(content, { filePath: filename });
    await ESLint.outputFixes(result);
  }
}
