import { IconSettings } from './icon-settings';

// tslint:disable:prettier
export const kirbyIconSettings: IconSettings = {
  icons: [
    { name: 'accounts-outline', svg: 'assets/kirby/icons/svg/accounts-outline.svg' },
    { name: 'accounts', svg: 'assets/kirby/icons/svg/accounts.svg' },
    { name: 'add', svg: 'assets/kirby/icons/svg/add.svg' },
    { name: 'unsubscribe', svg: 'assets/kirby/icons/svg/unsubscribe.svg' },
    { name: 'arrow-back', svg: 'assets/kirby/icons/svg/arrow-back.svg' },
    { name: 'arrow-down', svg: 'assets/kirby/icons/svg/arrow-down.svg' },
    { name: 'arrow-more', svg: 'assets/kirby/icons/svg/arrow-more.svg' },
    { name: 'arrow-up', svg: 'assets/kirby/icons/svg/arrow-up.svg' },
    { name: 'attach', svg: 'assets/kirby/icons/svg/attach.svg' },
    { name: 'backspace', svg: 'assets/kirby/icons/svg/backspace.svg' },
    { name: 'calendar', svg: 'assets/kirby/icons/svg/calendar.svg' },
    { name: 'camera', svg: 'assets/kirby/icons/svg/camera.svg' },
    { name: 'checkbox-outline', svg: 'assets/kirby/icons/svg/checkbox-outline.svg' },
    { name: 'checkbox', svg: 'assets/kirby/icons/svg/checkbox.svg' },
    { name: 'checkmark-selected', svg: 'assets/kirby/icons/svg/checkmark-selected.svg' },
    { name: 'close', svg: 'assets/kirby/icons/svg/close.svg' },
    { name: 'cog', svg: 'assets/kirby/icons/svg/cog.svg' },
    { name: 'copy', svg: 'assets/kirby/icons/svg/copy.svg' },
    { name: 'flag', svg: 'assets/kirby/icons/svg/flag.svg' },
    { name: 'edit', svg: 'assets/kirby/icons/svg/edit.svg' },
    { name: 'filter', svg: 'assets/kirby/icons/svg/filter.svg' },
    { name: 'flash-off', svg: 'assets/kirby/icons/svg/flash-off.svg' },
    { name: 'flash', svg: 'assets/kirby/icons/svg/flash.svg' },
    { name: 'moneybag', svg: 'assets/kirby/icons/svg/moneybag.svg' },
    { name: 'help', svg: 'assets/kirby/icons/svg/help.svg' },
    { name: 'inbox', svg: 'assets/kirby/icons/svg/inbox.svg' },
    { name: 'inbox-outline', svg: 'assets/kirby/icons/svg/inbox-outline.svg' },
    { name: 'information', svg: 'assets/kirby/icons/svg/information.svg' },
    { name: 'link', svg: 'assets/kirby/icons/svg/link.svg' },
    { name: 'log-out', svg: 'assets/kirby/icons/svg/log-out.svg' },
    { name: 'menu-outline', svg: 'assets/kirby/icons/svg/menu-outline.svg' },
    { name: 'menu', svg: 'assets/kirby/icons/svg/menu.svg' },
    { name: 'more', svg: 'assets/kirby/icons/svg/more.svg' },
    { name: 'move', svg: 'assets/kirby/icons/svg/move.svg' },
    { name: 'pension', svg: 'assets/kirby/icons/svg/pension.svg' },
    { name: 'person-outline', svg: 'assets/kirby/icons/svg/person-outline.svg' },
    { name: 'person', svg: 'assets/kirby/icons/svg/person.svg' },
    { name: 'qr', svg: 'assets/kirby/icons/svg/QR.svg' },
    { name: 'search', svg: 'assets/kirby/icons/svg/search.svg' },
    { name: 'share', svg: 'assets/kirby/icons/svg/share.svg' },
    { name: 'sort', svg: 'assets/kirby/icons/svg/sort.svg' },
    { name: 'support', svg: 'assets/kirby/icons/svg/support.svg' },
    { name: 'swap', svg: 'assets/kirby/icons/svg/swap.svg' },
    { name: 'trash', svg: 'assets/kirby/icons/svg/trash.svg' },
    { name: 'foreign-payment', svg: 'assets/kirby/icons/svg/foreign-payment.svg' },
    { name: 'clock', svg: 'assets/kirby/icons/svg/clock.svg' },
    { name: 'verify', svg: 'assets/kirby/icons/svg/verify.svg' },
    { name: 'warning', svg: 'assets/kirby/icons/svg/warning.svg' },
    { name: 'write-message', svg: 'assets/kirby/icons/svg/write-message.svg' },
    { name: 'reorder', svg: 'assets/kirby/icons/svg/reorder.svg' },
  ],
};

export const defaultIcons = kirbyIconSettings.icons.map((icon) => icon.name);
