import { exec } from 'child_process';
import { GenerateMocks } from '../tools/generate-mocks/dist/generate-mocks.js';

// We diff changes in /libs/core/src to make sure that changes to prop
// types (that unfortunately are not outputted to the proxies file) will result
// in mock generation. In the end prop type information is fetched from the
// custom-elements.json file, but we want to keep that out of git, as it
// is autogenerated every time core is built

const argv = process.argv;

// Any 'npm run' positional arguments after -- are used to pass --prefixed flags
// and options to the script which would otherwise be parsed by npm.
const terminator = '--';
const terminatorIndex = argv.indexOf(terminator);
function hasFlag(flag) {
  flag = terminator + flag;
  var pos = argv.indexOf(flag);
  return pos !== -1 && (terminatorIndex !== -1 ? pos < terminatorIndex : true);
}

const libRoot = './libs/designsystem/';
const coreSrc = './libs/core/src/';

function hasChanges() {
  return new Promise((resolve, reject) => {
    exec(
      // Exclude generated output (testing entry points) from the change detection:
      `git diff --name-only -- '${libRoot}' '${coreSrc}' ':(exclude)${libRoot}testing*'`,
      (e, stdout, stderr) => {
        if (e) return reject(e);
        if (stderr) return reject(stderr);
        return resolve(stdout.length > 0);
      }
    );
  });
}

function generateMocks() {
  const outputPaths = {
    base: './libs/designsystem/testing-base/src/lib/',
    jasmine: './libs/designsystem/testing-jasmine/src/lib/',
    jest: './libs/designsystem/testing-jest/src/lib/',
  };
  // core input path is not needed to generate angular mocks
  new GenerateMocks().renderMocks(libRoot, outputPaths);
}

hasChanges().then((hasChanged) => {
  if (!hasChanged && !hasFlag('force')) return;
  generateMocks();
});
