apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "spa.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "spa.name" . }}
{{- if .Values.git }}	
    git.repo: {{ .Values.git.repo }}	
    git.branch: {{ .Values.git.branch | replace "/" "__" }}	
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "25%"
      maxSurge: "25%"
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: {{ template "spa.name" . }}
    spec:
      containers:
      - name: {{ template "spa.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: web
          containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 1m
            memory: 20Mi
        livenessProbe:
          httpGet:
            path: /index.html
            port: web
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /index.html
            port: web
          initialDelaySeconds: 30
          timeoutSeconds: 5
{{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
{{- end }}
