apiVersion: v1
kind: Service
metadata:
  name: {{ template "spa.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "spa.name" . }}
spec:
  selector:
    app: {{ template "spa.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: web
    port: 80
    targetPort: web
