/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-docs-import-map.js
 * Run: node scripts/generate-docs-import-map.js
 *
 * This file is generated from the built design system package.
 * Make sure to build the design system first: nx build designsystem
 *
 * Note: Testing packages (testing, testing-base, testing-jasmine, testing-jest)
 * are excluded as they are for internal use only.
 *
 * This file contains the mapping of component/module/directive names
 * to their corresponding @kirbydesign/designsystem package paths.
 */

export interface ComponentToPackageMap {
  [componentName: string]: string;
}

export const COMPONENT_TO_PACKAGE_MAP: ComponentToPackageMap = {
  // .
  KeyHandlerDirective: '.',
  KirbyModule: '.',
  ModalRouterLinkDirective: '.',
  SegmentedControlComponent: '.',
  SegmentedControlMode: '.',
  SegmentItem: '.',

  // accordion
  AccordionDirective: 'accordion',
  AccordionItemComponent: 'accordion',
  AccordionModule: 'accordion',

  // action-group
  ACTIONGROUP_CONFIG: 'action-group',
  ActionGroupComponent: 'action-group',
  ActionGroupConfig: 'action-group',

  // avatar
  AvatarComponent: 'avatar',
  AvatarSize: 'avatar',

  // badge
  BadgeComponent: 'badge',
  BadgeSize: 'badge',

  // button
  AttentionLevel: 'button',
  ButtonComponent: 'button',
  ButtonSize: 'button',

  // calendar
  CalendarComponent: 'calendar',
  CalendarYearNavigatorConfig: 'calendar',
  Locale: 'calendar',

  // card
  CardAsButtonDirective: 'card',
  CardComponent: 'card',
  CardFlagLevel: 'card',
  CardFooterComponent: 'card',
  CardHeaderComponent: 'card',
  CardModule: 'card',

  // chart
  BarChartConfig: 'chart',
  BaseChartComponent: 'chart',
  ChartComponent: 'chart',
  ChartConfigService: 'chart',
  ChartDataLabelOptions: 'chart',
  ChartDataset: 'chart',
  ChartHighlightedElements: 'chart',
  ChartJSService: 'chart',
  ChartLabel: 'chart',
  ChartLocale: 'chart',
  ChartsModule: 'chart',
  ChartType: 'chart',
  ChartTypeConfig: 'chart',
  ChartTypesConfig: 'chart',
  StockChartComponent: 'chart',
  StockChartConfig: 'chart',
  TEST_CHART_ANNOTATIONS_CONFIG: 'chart',
  TEST_CHART_TYPES_CONFIG: 'chart',

  // checkbox
  CheckboxComponent: 'checkbox',

  // config
  KIRBY_CONFIG: 'config',
  KirbyConfig: 'config',

  // data-table
  DataTableModule: 'data-table',
  TableSortableComponent: 'data-table',

  // divider
  DividerComponent: 'divider',

  // dropdown
  DropdownComponent: 'dropdown',
  DropdownModule: 'dropdown',
  KeyboardHandlerService: 'dropdown',
  OpenState: 'dropdown',
  VerticalDirection: 'dropdown',

  // empty-state
  EmptyStateComponent: 'empty-state',
  EmptyStateModule: 'empty-state',

  // fab-sheet
  FabSheetComponent: 'fab-sheet',

  // flag
  FlagComponent: 'flag',
  FlagThemeColor: 'flag',

  // form-field
  AffixDirective: 'form-field',
  DateInputDirective: 'form-field',
  DecimalMaskDirective: 'form-field',
  FormFieldComponent: 'form-field',
  FormFieldMessageComponent: 'form-field',
  FormFieldModule: 'form-field',
  InputComponent: 'form-field',
  InputCounterComponent: 'form-field',
  InputSize: 'form-field',
  TextareaComponent: 'form-field',

  // header
  HeaderActionsDirective: 'header',
  HeaderComponent: 'header',
  HeaderCustomFlagDirective: 'header',
  HeaderCustomSectionDirective: 'header',
  HeaderModule: 'header',
  HeaderTitleActionIconDirective: 'header',

  // helpers
  IonicElementPartHelper: 'helpers',
  KirbyAnimation: 'helpers',
  LineClampHelper: 'helpers',
  PlatformService: 'helpers',
  StringSearchHelper: 'helpers',
  UniqueIdGenerator: 'helpers',

  // helpers/scss
  ScssHelper: 'helpers/scss',

  // icon
  BUILT_IN_ICONS_URL: 'icon',
  DEFAULT_BUILT_IN_ICONS_URL: 'icon',
  Icon: 'icon',
  IconComponent: 'icon',
  IconModule: 'icon',
  IconRegistryService: 'icon',
  IconSettings: 'icon',
  IconSize: 'icon',

  // item
  ItemComponent: 'item',
  ItemModule: 'item',
  ItemSize: 'item',
  LabelComponent: 'item',

  // item-group
  ItemGroupComponent: 'item-group',

  // item-sliding
  ItemSlidingComponent: 'item-sliding',
  ItemSlidingSide: 'item-sliding',
  ItemSwipeAction: 'item-sliding',
  ItemSwipeActionSlots: 'item-sliding',
  ItemSwipeActionType: 'item-sliding',

  // kirby-app
  AppComponent: 'kirby-app',
  KirbyAppModule: 'kirby-app',

  // list
  BoundaryClass: 'list',
  INFINITE_SCROLL_DEBOUNCE: 'list',
  InfiniteScrollDirective: 'list',
  ListComponent: 'list',
  ListExperimentalComponent: 'list',
  ListFooterDirective: 'list',
  ListHeaderComponent: 'list',
  ListHeaderDirective: 'list',
  ListHelper: 'list',
  ListItemColorDirective: 'list',
  ListItemComponent: 'list',
  ListItemTemplateDirective: 'list',
  ListModule: 'list',
  ListSectionHeaderComponent: 'list',
  ListSectionHeaderDirective: 'list',
  ListShape: 'list',
  ListSwipeAction: 'list',
  LoadOnDemandEvent: 'list',
  LoadOnDemandEventData: 'list',
  Scroll: 'list',
  StandAloneSpacing: 'list',

  // loading-overlay
  LoadingOverlayComponent: 'loading-overlay',
  LoadingOverlayService: 'loading-overlay',

  // menu
  MenuComponent: 'menu',

  // modal
  ActionSheetComponent: 'modal',
  ActionSheetConfig: 'modal',
  ActionSheetHelper: 'modal',
  ActionSheetItem: 'modal',
  AlertComponent: 'modal',
  AlertConfig: 'modal',
  AlertHelper: 'modal',
  CanDismissHelper: 'modal',
  CanDismissModalGuard: 'modal',
  COMPONENT_PROPS: 'modal',
  DrawerSupplementaryAction: 'modal',
  Modal: 'modal',
  ModalCompactWrapperComponent: 'modal',
  ModalComponent: 'modal',
  ModalConfig: 'modal',
  ModalController: 'modal',
  ModalElementComponent: 'modal',
  ModalElementsAdvertiser: 'modal',
  ModalElementType: 'modal',
  ModalEnabledRoutes: 'modal',
  ModalFlavor: 'modal',
  ModalFooterComponent: 'modal',
  ModalHelper: 'modal',
  ModalNavigationService: 'modal',
  ModalRouteActivation: 'modal',
  ModalSize: 'modal',
  ModalWrapperComponent: 'modal',
  Overlay: 'modal',
  OverlayEventDetail: 'modal',
  RoutedModalConfig: 'modal',
  ShowAlertCallback: 'modal',

  // page
  PAGE_BACK_BUTTON_OVERRIDE: 'page',
  PageActionsComponent: 'page',
  PageActionsDirective: 'page',
  PageBackButtonOverride: 'page',
  PageComponent: 'page',
  PageContentComponent: 'page',
  PageContentDirective: 'page',
  PageFooterComponent: 'page',
  PageModule: 'page',
  PageProgressComponent: 'page',
  PageStickyContentDirective: 'page',
  PageSubtitleDirective: 'page',
  PageTitleComponent: 'page',
  PageTitleDirective: 'page',
  PageToolbarTitleDirective: 'page',
  PullToRefreshEvent: 'page',

  // popover
  HorizontalDirection: 'popover',
  PopoverComponent: 'popover',

  // progress-circle
  ProgressCircleComponent: 'progress-circle',
  ProgressCircleRingComponent: 'progress-circle',

  // radio
  RadioComponent: 'radio',
  RadioGroupComponent: 'radio',
  RadioModule: 'radio',

  // range
  RangeComponent: 'range',

  // reorder-list
  ReorderEvent: 'reorder-list',
  ReorderListComponent: 'reorder-list',

  // router-outlet
  RouterOutletComponent: 'router-outlet',
  RouterOutletModule: 'router-outlet',

  // section-header
  SectionHeaderComponent: 'section-header',

  // shared
  ComponentConfiguration: 'shared',
  ComponentLoaderDirective: 'shared',
  DynamicComponent: 'shared',
  FitHeadingConfig: 'shared',
  FitHeadingDirective: 'shared',
  ResizeObserverFactory: 'shared',
  ResizeObserverService: 'shared',
  ThemeColorDirective: 'shared',
  TranslationService: 'shared',

  // shared/floating
  FloatingDirective: 'shared/floating',
  FloatingOffset: 'shared/floating',
  OutletSelector: 'shared/floating',
  PortalOutletConfig: 'shared/floating',
  TriggerEvent: 'shared/floating',

  // shared/portal
  PortalDirective: 'shared/portal',

  // slide
  KirbySwiperOptions: 'slide',
  SelectedSlide: 'slide',
  SlideDirective: 'slide',
  SlideModule: 'slide',
  SlidesComponent: 'slide',
  SlideStretchHeightDirective: 'slide',

  // slide-button
  SlideButtonComponent: 'slide-button',

  // spinner
  SpinnerComponent: 'spinner',
  SpinnerModule: 'spinner',

  // tab-navigation
  TabNavigationComponent: 'tab-navigation',
  TabNavigationItemComponent: 'tab-navigation',
  TabNavigationModule: 'tab-navigation',

  // tabs
  TabButtonComponent: 'tabs',
  TabsComponent: 'tabs',
  TabsModule: 'tabs',
  TabsService: 'tabs',

  // toast
  MessageType: 'toast',
  ToastConfig: 'toast',
  ToastController: 'toast',
  ToastHelper: 'toast',

  // toggle
  ToggleComponent: 'toggle',

  // toggle-button
  ToggleButtonComponent: 'toggle-button',
  ToggleButtonModule: 'toggle-button',

  // types
  EventListenerDisposeFn: 'types',
  FormFieldControl: 'types',
  UnobserveFn: 'types',
  WindowRef: 'types',
};
