/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: apps/cookbook/scripts/generate-import-map.js
 * Run: node apps/cookbook/scripts/generate-import-map.js
 *
 * This file contains the mapping of component/module/directive names
 * to their corresponding @kirbydesign/designsystem package paths.
 */

export interface ComponentToPackageMap {
  [componentName: string]: string;
}

export const COMPONENT_TO_PACKAGE_MAP: ComponentToPackageMap = {
  // accordion
  AccordionDirective: 'accordion',
  AccordionItemComponent: 'accordion',
  AccordionModule: 'accordion',

  // action-group
  ACTIONGROUP_CONFIG: 'action-group',
  ActionGroupComponent: 'action-group',
  ActionGroupConfig: 'action-group',

  // avatar
  AvatarComponent: 'avatar',
  AvatarSize: 'avatar',

  // badge
  BadgeComponent: 'badge',
  BadgeSize: 'badge',

  // button
  AttentionLevel: 'button',
  ButtonComponent: 'button',
  ButtonSize: 'button',

  // calendar
  CalendarComponent: 'calendar',
  CalendarYearNavigatorConfig: 'calendar',
  Locale: 'calendar',

  // card
  CardAsButtonDirective: 'card',
  CardComponent: 'card',
  CardFlagLevel: 'card',
  CardFooterComponent: 'card',
  CardHeaderComponent: 'card',
  CardModule: 'card',

  // chart
  BarChartConfig: 'chart',
  BaseChartComponent: 'chart',
  ChartComponent: 'chart',
  ChartConfigService: 'chart',
  ChartDataLabelOptions: 'chart',
  ChartDataset: 'chart',
  ChartHighlightedElements: 'chart',
  ChartJSService: 'chart',
  ChartLabel: 'chart',
  ChartLocale: 'chart',
  ChartsModule: 'chart',
  ChartType: 'chart',
  ChartTypeConfig: 'chart',
  ChartTypesConfig: 'chart',
  StockChartComponent: 'chart',
  StockChartConfig: 'chart',
  TEST_CHART_ANNOTATIONS_CONFIG: 'chart',
  TEST_CHART_TYPES_CONFIG: 'chart',

  // checkbox
  CheckboxComponent: 'checkbox',

  // config
  getGlobalConfig: 'config',
  KIRBY_CONFIG: 'config',
  KirbyConfig: 'config',

  // data-table
  DataTableModule: 'data-table',
  TableSortableComponent: 'data-table',

  // divider
  DividerComponent: 'divider',

  // dropdown
  DropdownComponent: 'dropdown',
  DropdownModule: 'dropdown',
  KeyboardHandlerService: 'dropdown',
  OpenState: 'dropdown',
  VerticalDirection: 'dropdown',

  // empty-state
  EmptyStateComponent: 'empty-state',
  EmptyStateModule: 'empty-state',

  // fab-sheet
  FabSheetComponent: 'fab-sheet',

  // flag
  FlagComponent: 'flag',
  FlagThemeColor: 'flag',

  // form-field
  AffixDirective: 'form-field',
  DateInputDirective: 'form-field',
  DecimalMaskDirective: 'form-field',
  FormFieldComponent: 'form-field',
  FormFieldMessageComponent: 'form-field',
  FormFieldModule: 'form-field',
  InputComponent: 'form-field',
  InputCounterComponent: 'form-field',
  InputSize: 'form-field',
  TextareaComponent: 'form-field',

  // header
  HeaderActionsDirective: 'header',
  HeaderComponent: 'header',
  HeaderCustomFlagDirective: 'header',
  HeaderCustomSectionDirective: 'header',
  HeaderModule: 'header',
  HeaderTitleActionIconDirective: 'header',

  // helpers
  BrandColor: 'helpers',
  Color: 'helpers',
  ColorHelper: 'helpers',
  DesignTokenHelper: 'helpers',
  Duration: 'helpers',
  Easing: 'helpers',
  IonicElementPartHelper: 'helpers',
  KirbyColor: 'helpers',
  LineClampHelper: 'helpers',
  NotificationColor: 'helpers',
  PlatformService: 'helpers',
  StringSearchHelper: 'helpers',
  ThemeColor: 'helpers',
  ThemeColorDefinition: 'helpers',
  ThemeColorExtended: 'helpers',
  ThemeColorVariant: 'helpers',
  UniqueIdGenerator: 'helpers',

  // icon
  BUILT_IN_ICONS_URL: 'icon',
  DEFAULT_BUILT_IN_ICONS_URL: 'icon',
  Icon: 'icon',
  IconComponent: 'icon',
  IconModule: 'icon',
  IconRegistryService: 'icon',
  IconSettings: 'icon',
  IconSize: 'icon',

  // item
  ItemComponent: 'item',
  ItemModule: 'item',
  ItemSize: 'item',
  LabelComponent: 'item',

  // item-group
  ItemGroupComponent: 'item-group',

  // item-sliding
  ItemSlidingComponent: 'item-sliding',
  ItemSlidingSide: 'item-sliding',
  ItemSwipeAction: 'item-sliding',
  ItemSwipeActionSlots: 'item-sliding',
  ItemSwipeActionType: 'item-sliding',

  // kirby-app
  AppComponent: 'kirby-app',
  KirbyAppModule: 'kirby-app',

  // list
  BoundaryClass: 'list',
  INFINITE_SCROLL_DEBOUNCE: 'list',
  InfiniteScrollDirective: 'list',
  ListComponent: 'list',
  ListExperimentalComponent: 'list',
  ListFooterDirective: 'list',
  ListHeaderComponent: 'list',
  ListHeaderDirective: 'list',
  ListHelper: 'list',
  ListItemColorDirective: 'list',
  ListItemComponent: 'list',
  ListItemTemplateDirective: 'list',
  ListModule: 'list',
  ListSectionHeaderComponent: 'list',
  ListSectionHeaderDirective: 'list',
  ListShape: 'list',
  ListSwipeAction: 'list',
  LoadOnDemandEvent: 'list',
  LoadOnDemandEventData: 'list',
  Scroll: 'list',
  StandAloneSpacing: 'list',

  // loading-overlay
  LoadingOverlayComponent: 'loading-overlay',
  LoadingOverlayService: 'loading-overlay',

  // menu
  MenuComponent: 'menu',

  // modal
  ActionSheetComponent: 'modal',
  ActionSheetConfig: 'modal',
  ActionSheetHelper: 'modal',
  ActionSheetItem: 'modal',
  AlertComponent: 'modal',
  AlertConfig: 'modal',
  AlertHelper: 'modal',
  CanDismissHelper: 'modal',
  CanDismissModalGuard: 'modal',
  COMPONENT_PROPS: 'modal',
  DrawerSupplementaryAction: 'modal',
  ModalCompactWrapperComponent: 'modal',
  ModalComponent: 'modal',
  ModalConfig: 'modal',
  ModalController: 'modal',
  ModalElementType: 'modal',
  ModalEnabledRoutes: 'modal',
  ModalFlavor: 'modal',
  ModalFooterComponent: 'modal',
  ModalHelper: 'modal',
  ModalNavigationService: 'modal',
  ModalRouteActivation: 'modal',
  ModalSize: 'modal',
  ModalWrapperComponent: 'modal',
  Overlay: 'modal',
  OverlayEventDetail: 'modal',
  RoutedModalConfig: 'modal',
  ShowAlertCallback: 'modal',

  // page
  PAGE_BACK_BUTTON_OVERRIDE: 'page',
  PageActionsComponent: 'page',
  PageActionsDirective: 'page',
  PageBackButtonOverride: 'page',
  PageComponent: 'page',
  PageContentComponent: 'page',
  PageContentDirective: 'page',
  PageFooterComponent: 'page',
  PageModule: 'page',
  PageProgressComponent: 'page',
  PageStickyContentDirective: 'page',
  PageSubtitleDirective: 'page',
  PageTitleComponent: 'page',
  PageTitleDirective: 'page',
  PageToolbarTitleDirective: 'page',
  PullToRefreshEvent: 'page',

  // popover
  HorizontalDirection: 'popover',
  PopoverComponent: 'popover',

  // progress-circle
  ProgressCircleComponent: 'progress-circle',
  ProgressCircleRingComponent: 'progress-circle',

  // radio
  RadioComponent: 'radio',
  RadioGroupComponent: 'radio',
  RadioModule: 'radio',

  // range
  RangeComponent: 'range',

  // reorder-list
  ReorderEvent: 'reorder-list',
  ReorderListComponent: 'reorder-list',

  // router-outlet
  NavController: 'router-outlet',
  RouterOutletComponent: 'router-outlet',
  RouterOutletModule: 'router-outlet',

  // section-header
  SectionHeaderComponent: 'section-header',

  // shared
  ComponentConfiguration: 'shared',
  ComponentLoaderDirective: 'shared',
  DynamicComponent: 'shared',
  FitHeadingConfig: 'shared',
  FitHeadingDirective: 'shared',
  ResizeObserverFactory: 'shared',
  ResizeObserverService: 'shared',
  ThemeColorDirective: 'shared',
  TranslationService: 'shared',

  // slide
  KirbySwiperOptions: 'slide',
  SelectedSlide: 'slide',
  SlideDirective: 'slide',
  SlideModule: 'slide',
  SlidesComponent: 'slide',
  SlideStretchHeightDirective: 'slide',

  // slide-button
  SlideButtonComponent: 'slide-button',

  // spinner
  SpinnerComponent: 'spinner',
  SpinnerModule: 'spinner',

  // tab-navigation
  TabNavigationComponent: 'tab-navigation',
  TabNavigationItemComponent: 'tab-navigation',
  TabNavigationModule: 'tab-navigation',

  // tabs
  IonRouterOutlet: 'tabs',
  TabButtonComponent: 'tabs',
  TabsComponent: 'tabs',
  TabsModule: 'tabs',
  TabsService: 'tabs',

  // testing
  ElementCssCustomMatchers: 'testing',
  ScreenSize: 'testing',
  TestHelper: 'testing',

  // testing-base
  KirbyTestingBaseModule: 'testing-base',
  MockAccordionDirective: 'testing-base',
  MockAccordionItemComponent: 'testing-base',
  MockActionGroupComponent: 'testing-base',
  MockActionSheetComponent: 'testing-base',
  MockAffixDirective: 'testing-base',
  MockAlertComponent: 'testing-base',
  MockAppComponent: 'testing-base',
  MockAvatarComponent: 'testing-base',
  MockBadgeComponent: 'testing-base',
  MockBaseChartComponent: 'testing-base',
  MockButtonComponent: 'testing-base',
  MockCalendarComponent: 'testing-base',
  MockCardAsButtonDirective: 'testing-base',
  MockCardComponent: 'testing-base',
  MockCardFooterComponent: 'testing-base',
  MockCardHeaderComponent: 'testing-base',
  MockChartComponent: 'testing-base',
  MockCheckboxComponent: 'testing-base',
  MockComponentLoaderDirective: 'testing-base',
  MockDateInputDirective: 'testing-base',
  MockDecimalMaskDirective: 'testing-base',
  MockDividerComponent: 'testing-base',
  MockDropdownComponent: 'testing-base',
  MockEmptyStateComponent: 'testing-base',
  MockFabSheetComponent: 'testing-base',
  MockFitHeadingDirective: 'testing-base',
  MockFlagComponent: 'testing-base',
  MockFloatingDirective: 'testing-base',
  MockFormFieldComponent: 'testing-base',
  MockFormFieldMessageComponent: 'testing-base',
  MockHeaderActionsDirective: 'testing-base',
  MockHeaderComponent: 'testing-base',
  MockHeaderCustomSectionDirective: 'testing-base',
  MockIconComponent: 'testing-base',
  MockInfiniteScrollDirective: 'testing-base',
  MockInputComponent: 'testing-base',
  MockInputCounterComponent: 'testing-base',
  MockItemComponent: 'testing-base',
  MockItemGroupComponent: 'testing-base',
  MockItemSlidingComponent: 'testing-base',
  MockKeyHandlerDirective: 'testing-base',
  MockLabelComponent: 'testing-base',
  MockListComponent: 'testing-base',
  MockListExperimentalComponent: 'testing-base',
  MockListFooterDirective: 'testing-base',
  MockListHeaderComponent: 'testing-base',
  MockListHeaderDirective: 'testing-base',
  MockListItemColorDirective: 'testing-base',
  MockListItemComponent: 'testing-base',
  MockListItemTemplateDirective: 'testing-base',
  MockListSectionHeaderComponent: 'testing-base',
  MockListSectionHeaderDirective: 'testing-base',
  MockLoadingOverlayComponent: 'testing-base',
  MockMenuComponent: 'testing-base',
  MockModalCompactWrapperComponent: 'testing-base',
  MockModalFooterComponent: 'testing-base',
  MockModalRouterLinkDirective: 'testing-base',
  MockModalWrapperComponent: 'testing-base',
  MockPageActionsComponent: 'testing-base',
  MockPageActionsDirective: 'testing-base',
  MockPageComponent: 'testing-base',
  MockPageContentComponent: 'testing-base',
  MockPageContentDirective: 'testing-base',
  MockPageFooterComponent: 'testing-base',
  MockPageProgressComponent: 'testing-base',
  MockPageStickyContentDirective: 'testing-base',
  MockPageSubtitleDirective: 'testing-base',
  MockPageTitleComponent: 'testing-base',
  MockPageTitleDirective: 'testing-base',
  MockPageToolbarTitleDirective: 'testing-base',
  MockPopoverComponent: 'testing-base',
  MockPortalDirective: 'testing-base',
  MockProgressCircleComponent: 'testing-base',
  MockProgressCircleRingComponent: 'testing-base',
  MockRadioComponent: 'testing-base',
  MockRadioGroupComponent: 'testing-base',
  MockRangeComponent: 'testing-base',
  MockReorderListComponent: 'testing-base',
  MockRouterOutletComponent: 'testing-base',
  MockSectionHeaderComponent: 'testing-base',
  MockSegmentedControlComponent: 'testing-base',
  MockSlideButtonComponent: 'testing-base',
  MockSlideDirective: 'testing-base',
  MockSlidesComponent: 'testing-base',
  MockSpinnerComponent: 'testing-base',
  MockStockChartComponent: 'testing-base',
  MockTabButtonComponent: 'testing-base',
  MockTabNavigationComponent: 'testing-base',
  MockTabNavigationItemComponent: 'testing-base',
  MockTabsComponent: 'testing-base',
  MockTextareaComponent: 'testing-base',
  MockThemeColorDirective: 'testing-base',
  MockToggleButtonComponent: 'testing-base',
  MockToggleComponent: 'testing-base',

  // testing-jest
  KirbyTestingModule: 'testing-jest',

  // toast
  MessageType: 'toast',
  ToastConfig: 'toast',
  ToastController: 'toast',
  ToastHelper: 'toast',

  // toggle
  ToggleComponent: 'toggle',

  // toggle-button
  ToggleButtonComponent: 'toggle-button',
  ToggleButtonModule: 'toggle-button',

  // types
  EventListenerDisposeFn: 'types',
  FormFieldControl: 'types',
  UnobserveFn: 'types',
  WindowRef: 'types',
};
