import { CustomIconSettings } from '@kirbydesign/designsystem/components/icon/custom-icon-settings';

// tslint:disable:prettier
export const kirbyCustomIconSettings: CustomIconSettings = {
  fontfamily: 'kirby',
  icons: [
    { name: 'accounts-outline', svg: 'assets/icons/kirby/accounts-outline.svg', unicode: '0xe900' },
    { name: 'accounts', svg: 'assets/icons/kirby/accounts.svg', unicode: '0xe901' },
    { name: 'add', svg: 'assets/icons/kirby/add.svg', unicode: '0xe902' },
    { name: 'unsubscribe', svg: 'assets/icons/kirby/unsubscribe.svg', unicode: '0xe903' },
    { name: 'arrow-back', svg: 'assets/icons/kirby/arrow-back.svg', unicode: '0xe904' },
    { name: 'arrow-down', svg: 'assets/icons/kirby/arrow-down.svg', unicode: '0xe905' },
    { name: 'arrow-more', svg: 'assets/icons/kirby/arrow-more.svg', unicode: '0xe906' },
    { name: 'arrow-up', svg: 'assets/icons/kirby/arrow-up.svg', unicode: '0xe907' },
    { name: 'attach', svg: 'assets/icons/kirby/attach.svg', unicode: '0xe908' },
    { name: 'calendar', svg: 'assets/icons/kirby/calendar.svg', unicode: '0xe909' },
    { name: 'checkbox-outline', svg: 'assets/icons/kirby/checkbox-outline.svg', unicode: '0xe90a' },
    { name: 'checkbox', svg: 'assets/icons/kirby/checkbox.svg', unicode: '0xe90b' },
    { name: 'close', svg: 'assets/icons/kirby/close.svg', unicode: '0xe90c' },
    { name: 'cog', svg: 'assets/icons/kirby/cog.svg', unicode: '0xe90d' },
    { name: 'edit', svg: 'assets/icons/kirby/edit.svg', unicode: '0xe90e' },
    { name: 'filter', svg: 'assets/icons/kirby/filter.svg', unicode: '0xe90f' },
    { name: 'flash-off', svg: 'assets/icons/kirby/flash-off.svg', unicode: '0xe910' },
    { name: 'flash', svg: 'assets/icons/kirby/flash.svg', unicode: '0xe911' },
    { name: 'moneybag', svg: 'assets/icons/kirby/moneybag.svg', unicode: '0xe912' },
    { name: 'help', svg: 'assets/icons/kirby/help.svg', unicode: '0xe913' },
    { name: 'inbox-outline', svg: 'assets/icons/kirby/inbox-outline.svg', unicode: '0xe914' },
    { name: 'inbox', svg: 'assets/icons/kirby/inbox.svg', unicode: '0xe915' },
    { name: 'link', svg: 'assets/icons/kirby/link.svg', unicode: '0xe916' },
    { name: 'log-out', svg: 'assets/icons/kirby/log-out.svg', unicode: '0xe917' },
    { name: 'menu-outline', svg: 'assets/icons/kirby/menu-outline.svg', unicode: '0xe918' },
    { name: 'menu', svg: 'assets/icons/kirby/menu.svg', unicode: '0xe919' },
    { name: 'more', svg: 'assets/icons/kirby/more.svg', unicode: '0xe91a' },
    { name: 'move', svg: 'assets/icons/kirby/move.svg', unicode: '0xe91b' },
    { name: 'pension', svg: 'assets/icons/kirby/pension.svg', unicode: '0xe91c' },
    { name: 'person-outline', svg: 'assets/icons/kirby/person-outline.svg', unicode: '0xe91d' },
    { name: 'person', svg: 'assets/icons/kirby/person.svg', unicode: '0xe91e' },
    { name: 'qr', svg: 'assets/icons/kirby/QR.svg', unicode: '0xe91f' },
    { name: 'search', svg: 'assets/icons/kirby/search.svg', unicode: '0xe920' },
    { name: 'share', svg: 'assets/icons/kirby/share.svg', unicode: '0xe921' },
    { name: 'sort', svg: 'assets/icons/kirby/sort.svg', unicode: '0xe922' },
    { name: 'swap', svg: 'assets/icons/kirby/swap.svg', unicode: '0xe923' },
    { name: 'trash', svg: 'assets/icons/kirby/trash.svg', unicode: '0xe924' },
    { name: 'foreign-payment', svg: 'assets/icons/kirby/foreign-payment.svg', unicode: '0xe925' },
    { name: 'clock', svg: 'assets/icons/kirby/clock.svg', unicode: '0xe926' },
    { name: 'verifiy', svg: 'assets/icons/kirby/verifiy.svg', unicode: '0xe927' },
    { name: 'warning', svg: 'assets/icons/kirby/warning.svg', unicode: '0xe928' },
    { name: 'write-message', svg: 'assets/icons/kirby/write-message.svg', unicode: '0xe929' },
  ],
};
