import { IconSettings } from '@kirbydesign/designsystem/components/icon/icon-settings';

// tslint:disable:prettier
export const kirbyIconSettings: IconSettings = {
  fontfamily: 'kirby',
  icons: [
    { name: 'accounts-outline', svg: 'assets/kirby/icons/svg/accounts-outline.svg', unicode: 0xe900 },
    { name: 'accounts', svg: 'assets/kirby/icons/svg/accounts.svg', unicode: 0xe901 },
    { name: 'add', svg: 'assets/kirby/icons/svg/add.svg', unicode: 0xe902 },
    { name: 'unsubscribe', svg: 'assets/kirby/icons/svg/unsubscribe.svg', unicode: 0xe903 },
    { name: 'arrow-back', svg: 'assets/kirby/icons/svg/arrow-back.svg', unicode: 0xe904 },
    { name: 'arrow-down', svg: 'assets/kirby/icons/svg/arrow-down.svg', unicode: 0xe905 },
    { name: 'arrow-more', svg: 'assets/kirby/icons/svg/arrow-more.svg', unicode: 0xe906 },
    { name: 'arrow-up', svg: 'assets/kirby/icons/svg/arrow-up.svg', unicode: 0xe907 },
    { name: 'attach', svg: 'assets/kirby/icons/svg/attach.svg', unicode: 0xe908 },
    { name: 'calendar', svg: 'assets/kirby/icons/svg/calendar.svg', unicode: 0xe909 },
    { name: 'checkbox-outline', svg: 'assets/kirby/icons/svg/checkbox-outline.svg', unicode: 0xe90a },
    { name: 'checkbox', svg: 'assets/kirby/icons/svg/checkbox.svg', unicode: 0xe90b },
    { name: 'close', svg: 'assets/kirby/icons/svg/close.svg', unicode: 0xe90c },
    { name: 'cog', svg: 'assets/kirby/icons/svg/cog.svg', unicode: 0xe90d },
    { name: 'edit', svg: 'assets/kirby/icons/svg/edit.svg', unicode: 0xe90e },
    { name: 'filter', svg: 'assets/kirby/icons/svg/filter.svg', unicode: 0xe90f },
    { name: 'flash-off', svg: 'assets/kirby/icons/svg/flash-off.svg', unicode: 0xe910 },
    { name: 'flash', svg: 'assets/kirby/icons/svg/flash.svg', unicode: 0xe911 },
    { name: 'moneybag', svg: 'assets/kirby/icons/svg/moneybag.svg', unicode: 0xe912 },
    { name: 'help', svg: 'assets/kirby/icons/svg/help.svg', unicode: 0xe913 },
    { name: 'inbox-outline', svg: 'assets/kirby/icons/svg/inbox-outline.svg', unicode: 0xe914 },
    { name: 'inbox', svg: 'assets/kirby/icons/svg/inbox.svg', unicode: 0xe915 },
    { name: 'link', svg: 'assets/kirby/icons/svg/link.svg', unicode: 0xe916 },
    { name: 'log-out', svg: 'assets/kirby/icons/svg/log-out.svg', unicode: 0xe917 },
    { name: 'menu-outline', svg: 'assets/kirby/icons/svg/menu-outline.svg', unicode: 0xe918 },
    { name: 'menu', svg: 'assets/kirby/icons/svg/menu.svg', unicode: 0xe919 },
    { name: 'more', svg: 'assets/kirby/icons/svg/more.svg', unicode: 0xe91a },
    { name: 'move', svg: 'assets/kirby/icons/svg/move.svg', unicode: 0xe91b },
    { name: 'pension', svg: 'assets/kirby/icons/svg/pension.svg', unicode: 0xe91c },
    { name: 'person-outline', svg: 'assets/kirby/icons/svg/person-outline.svg', unicode: 0xe91d },
    { name: 'person', svg: 'assets/kirby/icons/svg/person.svg', unicode: 0xe91e },
    { name: 'qr', svg: 'assets/kirby/icons/svg/QR.svg', unicode: 0xe91f },
    { name: 'search', svg: 'assets/kirby/icons/svg/search.svg', unicode: 0xe920 },
    { name: 'share', svg: 'assets/kirby/icons/svg/share.svg', unicode: 0xe921 },
    { name: 'sort', svg: 'assets/kirby/icons/svg/sort.svg', unicode: 0xe922 },
    { name: 'swap', svg: 'assets/kirby/icons/svg/swap.svg', unicode: 0xe923 },
    { name: 'trash', svg: 'assets/kirby/icons/svg/trash.svg', unicode: 0xe924 },
    { name: 'foreign-payment', svg: 'assets/kirby/icons/svg/foreign-payment.svg', unicode: 0xe925 },
    { name: 'clock', svg: 'assets/kirby/icons/svg/clock.svg', unicode: 0xe926 },
    { name: 'verifiy', svg: 'assets/kirby/icons/svg/verifiy.svg', unicode: 0xe927 },
    { name: 'warning', svg: 'assets/kirby/icons/svg/warning.svg', unicode: 0xe928 },
    { name: 'write-message', svg: 'assets/kirby/icons/svg/write-message.svg', unicode: 0xe929 },
  ],
};
