name: Kirby CI for branch pushes

on:
  push:

jobs:
  lint_and_unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo Event ${{ github.event.type }}
      - run: pip install six
      - run: npm ci
      - run: npm run lint
      - run: npm run extract-scss-variables
      - run: npm run test:ci
      - run: npm run coverage-report || true

  build_kirby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          registry-url: https://registry.npmjs.org
          node-version: ${{ matrix.node-version }}
        env:
          NODE_AUTH_TOKEN: $ {{ NPM_AUTH_TOKEN }}
      - run: pip install six
      - run: npm ci
      - run: npm run dist:designsystem
