name: Clean up branch deployment
on:
  delete

jobs:
  delete_latest_deployment_for_branch:
    name: Delete latest deployment for branch
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Get latest deployment for branch
        id: get_latest_deployment
        run: |
          ref="${{ startsWith(github.event.ref, 'refs/heads/') && '' || 'refs/heads/' }}${{ github.event.ref }}"
          deployment_id=$(gh api "/repos/${{ github.repository }}/deployments?ref=${ref}" --jq '.[0].id // empty')
          echo "id=${deployment_id}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set deployment status to inactive
        if: steps.get_latest_deployment.outputs.id != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOYMENT_STATE: inactive
        run: |
          gh api /repos/${{ github.repository }}/deployments/${{ steps.get_latest_deployment.outputs.id }}/statuses \
            --method POST \
            -f state="$DEPLOYMENT_STATE" \
            -f log_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Delete deployment
        if: steps.get_latest_deployment.outputs.id != ''
        run: |
          gh api /repos/${{ github.repository }}/deployments/${{ steps.get_latest_deployment.outputs.id }} \
            --method DELETE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
