# This is a basic workflow to help you get started with Actions

name: Kirby CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint_and_unittest:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
      - run: npm run extract-scss-variables
      - run : npm run test:ci
      - run : npm run coverage-report || true
  
  build_kirby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test


