# This is a basic workflow to help you get started with Actions

name: Kirby CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint_and_unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo Event ${{ github.event.type }}
      - run: pip install six
      - run: npm ci
      - run: npm run lint
      - run: npm run extract-scss-variables
      - run: npm run test:ci
      - run: npm run coverage-report || true

  build_kirby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          registry-url: https://registry.npmjs.org
          node-version: ${{ matrix.node-version }}
        env:
          NODE_AUTH_TOKEN: $ {{ NPM_AUTH_TOKEN }}
      - run: pip install six
      - run: npm ci
      - run: npm run dist:designsystem

  deploy_to_cookbook:
    needs: [lint_and_unittest, build_kirby]
    if: github.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16]
    steps:
      - uses: actions/checkout@v2
                    

