name: Publish new versions to npm

# Tags starting with 'v' are protected tags and can only be pushed by admins.
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  id-token: write  # Required for OIDC (https://docs.github.com/en/actions/concepts/security/openid-connect)
  contents: read

jobs:
  publish_packages:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Kirby setup
        uses: ./.github/actions/kirby-setup
      - name: Build core package and publish to npm
        run: npm run publish -- core
      - name: Build designsystem package and publish to npm
        run: npm run publish -- designsystem
