name: Test publish script

on:
  push:
    branches: chore/fix-publish

defaults:
  run:
    shell: bash

jobs:
  bump_version_and_publish:
    name: Run publish script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: refs/heads/master
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.16'
      - name: Install NPM dependencies
        run: npm ci
      - name: Build package
        run: echo node ./.scripts/publish.js
