name: Spot Illustrations

on:
  pull_request:
    paths:
      - 'libs/extensions/angular/spot-illustration/src/svgs/**'

jobs:
  validate:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run SVG validator
        run: python spot_illustration_validator.py libs/extensions/angular/spot-illustration/src/svgs
