name: Spot Illustrations

on:
  pull_request:
    paths:
      - 'libs/extensions/angular/spot-illustration/src/svgs/**'

permissions:
  contents: read

jobs:
  validate:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'

      - name: Run SVG validator
        run: python scripts/spot-illustration-validator.py libs/extensions/angular/spot-illustration/src/svgs
