name: CI-test

on:
  push:

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: decrypt kube config
        env:
          encrypted_09e556d51fdc_key: ${{secrets.ENCRYPTED_09E556D51FDC_KEY}}
          encrypted_09e556d51fdc_iv: ${{secrets.ENCRYPTED_09E556D51FDC_IV}}
        run: |
          echo $encrypted_09e556d51fdc_key
          echo $encrypted_09e556d51fdc_iv
          openssl version
          
