name: CI-test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: branch name modifications
        env:
          RELEASE_NAME: ''
          FEATURE: 'feature'
        run: |
          echo "RELEASE_NAME=${GITHUB_REF##*/}"
          echo "RELEASE_NAME=${RELEASE_NAME}//${FEATURE}\//"
          echo "RELEASE_NAME=${RELEASE_NAME}#?"
          echo "RELEASE_NAME="$GIT_REPO-$RELEASE_NAME//[^a-zA-Z0-9]/-"
          echo "RELEASE_NAME=$(tr [A-Z] [a-z] <<< $RELEASE_NAME)"
          echo "RELEASE_NAME=$(cut -c 1-53 <<< $RELEASE_NAME)"
          echo $RELEASE_NAME
