name: CI-test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: branch name modifications
        run: |
          echo "RELEASE_NAME=${GITHUB_REF##*/}" >> @GITHUB_ENV
      - name: print
        run: echo branch is ${{ env.NAME }}
      - name: src
        run: echo ${GITHUB_REF##*/}
  
