# This is a basic workflow to help you get started with Actions

name: tester

# Controls when the action will run. 
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        if: "!startsWith(github.event.head_commit.message, 'Bumping version to') && github.ref != 'refs/heads/master'"
      - name: tester step
        env:
          DOMAIN: ${{ github.ref == 'refs/heads/master' && 'kirby.design' || '650b277bd9a54e5cbadc.westeurope.aksapp.io' }}
          HELM_CONFIG: ${{ github.ref == 'refs/heads/master' && 'config/helm/staging.yaml' || 'config/helm/branch.yaml' }}
        run: |
          echo Domain $DOMAIN
          echo HELM_CONFIG $HELM_CONFIG
          
