name: CI-test

on:
  push:

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: get branch name
        run: |
          gref="${GITHUB_REF##*/}"
          echo $gref
          ref="${gref//test//-}"
          echo $ref
