name: CI-test

on:
  push:

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: get branch name
        run: |
          branchname="${GITHUB_REF##*/}"
          echo $branchname
          branchname="${branchname//test//-}"
          echo $branchname
          releasename="designsystem-${branchname//[^a-zA-Z0-9]/-}"
          echo $releasename
          releasename=$(tr [A-Z] [a-z] <<< "$releasename")
          echo $releasename
          releasename=$(cut -c 1-53 <<< "$releasename")
          echo $releasename
          
