name: CI-test

on:
  push:

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: decrypt kube config
        env:
          encrypted_09e556d51fdc_key: ${{secrets.ENCRYPTED_09E556D51FDC_KEY}}
          encrypted_09e556d51fdc_iv: ${{secrets.ENCRYPTED_09E556D51FDC_IV}}
        run: |
          openssl version
          openssl aes-256-cbc -K $encrypted_09e556d51fdc_key -iv $encrypted_09e556d51fdc_iv -in ./.scripts/kube-config.enc -out kube.config -d
          
