name: Kirby master CI
on: push
    
defaults:
  run:
    shell: bash

jobs:
  doIt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: get tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: print
        run: echo @RELEASE_VERSION
