name: CI-test

on:
  push:

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: get branch name
        run: |
          echo "${GITHUB_REF##*/}
          name = "${GITHUB_REF##*/}"
          echo $name
          ref="${github_ref////-}"
          echo $ref
      - name: Use environment variables
        run: echo "GIT_BRANCH=${GIT_BRANCH}"
