name: CI-test

on:
  push:

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get branch name
        run: |
          branchname="${GITHUB_REF##*/}"
          branchname="${branchname//feature//}"
          branchname="${branchname#?}"
          releasename="designsystem-${branchname//[^a-zA-Z0-9]/-}"
          releasename=$(tr [A-Z] [a-z] <<< "$releasename")
          releasename=$(cut -c 1-53 <<< "$releasename")
          echo "RELEASENAME=${releasename}" >> $GITHUB_ENV
      - name: get dns
        env:
          DOMAIN: '650b277bd9a54e5cbadc.westeurope.aksapp.io'
        run: |
          chmod +x ./.scripts/dns.pl
          dns=$(perl ./.scripts/dns.pl $DOMAIN "${RELEASENAME}")
          echo "dns became $dns"
      - name: handle branches
        if: ${{ github.ref != 'refs/heads/master' }}
        run: echo "release name from env ${RELEASENAME}"
          
