name: CI-test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: branch name modifications
        env:
          RELEASE_NAME: ''
          FEATURE: 'feature'
      - name: generate release name for brances
        if: ${{ github.ref != 'refs/heads/master' }}
        run:  echo "RELEASE_NAME=${GITHUB_REF##*/}"
      
