name: CI-test

on:
  push:

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: get branch name
        env:
          NODE_OPTIONS: '--max_old_space_size=3072'
          DOMAIN: '650b277bd9a54e5cbadc.westeurope.aksapp.io'
        run: |
          branchname="${GITHUB_REF##*/}"
          branchname="${branchname//feature//}"
          branchname="${branchname#?}"
          releasename="designsystem-${branchname//[^a-zA-Z0-9]/-}"
          releasename=$(tr [A-Z] [a-z] <<< "$releasename")
          releasename=$(cut -c 1-53 <<< "$releasename")
          echo "RELEASENAME=${releasename}" >> $GITHUB_ENV
      - name: get dns
        run: |
          echo $PWD
          dns=$('sh .scripts/dns.pl ${DOMAIN} ${RELEASENAME}')
          echo $dns
      - name: handle branches
        if: ${{ github.ref != 'refs/heads/master' }}
        run: echo "release name from env ${RELEASENAME}"
          
