name: CI-test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: branch name modifications
        env:
          RELEASE_NAME: ''
          FEATURE: 'feature'
        run: |
          echo "RELEASE_NAME=${GITHUB_REF##*/}"
          echo $RELEASE_NAME
