name: CI-test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: branch name modifications
        env:
          FEATURE: 'feature'
          NAME: ${{GITHUB_REF}}
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          echo "RELEASE_NAME=$GITHUB_REF##*/" >> @GITHUB_ENV
          echo bname ${{env.NAME}}
        
  
